export const economyMetricTooltips = {
  monthlyIncome: 'Total de ingresos completados del mes indicado. Suma movimientos de tipo INGRESOS con estado COMPLETADO dentro del período mensual correspondiente.',
  monthlyExpenses: 'Total de egresos completados del mes indicado. Suma movimientos de tipo EGRESOS con estado COMPLETADO dentro del período mensual correspondiente.',
  monthlyBalance: 'Resultado financiero del mes indicado. Se calcula como ingresos completados del mes menos egresos completados del mes. Fórmula: Balance = Ingresos - Egresos.',
  liquidity: 'Disponibilidad actual de las cuentas del circuito financiero, respetando el corte de arranque aprobado. Sólo los movimientos completados con efecto de caja modifican este saldo.',
  projectedBalance: 'Proyección del circuito financiero vigente a partir de liquidez y sus componentes de cobros, pagos y liquidaciones. Consulte el detalle y sus supuestos debajo de las tarjetas.',
  incomeVariation: 'Compara los ingresos completados del último mes completo contra el mes anterior. Fórmula: ((Ingresos mes actual - Ingresos mes anterior) / Ingresos mes anterior) × 100.',
  expensesVariation: 'Compara los egresos completados del último mes completo contra el mes anterior. Fórmula: ((Egresos mes actual - Egresos mes anterior) / Egresos mes anterior) × 100.',
  utilityVariation: 'Compara la utilidad del último mes completo contra el mes anterior. La utilidad se calcula como Ingresos - Egresos. Fórmula: ((Utilidad actual - Utilidad anterior) / Utilidad anterior) × 100.',
  growth: 'Mide el crecimiento general del club combinando evolución económica y evolución de clientes. Crecimiento Económico: variación de ingresos del último mes completo contra el mes anterior. Crecimiento de Clientes: variación de inscriptos acumulados al cierre de cada mes. Fórmula: (Crecimiento Económico + Crecimiento de Clientes) / 2.',
  operatingProfitability: 'Mide el resultado operativo del club. Se calcula como ingresos completados menos egresos completados cuya metadata persistida los clasifica como operativos.',
  nonOperatingExpenses: 'Mide el balance de movimientos cuya metadata persistida los clasifica como no operativos.',
  services: 'Agrupa el balance de movimientos clasificados como servicios en el catálogo persistido.',
  taxes: 'Balance de movimientos completados clasificados como impuestos. Fórmula: Ingresos - Egresos.',
  debtLiabilities: 'Balance de movimientos completados clasificados como pasivos. Fórmula: Ingresos - Egresos.',
} as const;
