import type { OnboardingActivityDraft, OnboardingSectorDraft, OnboardingWorkerDraft } from '@miclub/shared';
import { useState, type FormEvent } from 'react';
import { DraftEditorModal } from './DraftEditorModal';

const icons = ['⚽','🏀','🏐','🏉','🎾','🏓','🏸','🏑','🏒','🥊','🥋','🤸','🏋️','🤾','🏊','🤽','🚴','🏃','🧘','💃','⛸️','🎯','♟️','🏹'];
const statusLabel = { active:'Activa', inactive:'Inactiva' };
export function ActivityDraftList({ items, sectors, workers, onChange }: { items: OnboardingActivityDraft[]; sectors: OnboardingSectorDraft[]; workers: OnboardingWorkerDraft[]; onChange:(items:OnboardingActivityDraft[])=>void }) {
  const [editing,setEditing]=useState<OnboardingActivityDraft|null>();
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),mode=String(data.get('settlementMode')) as OnboardingActivityDraft['settlementMode'];const activity:OnboardingActivityDraft={clientId:editing?.clientId??crypto.randomUUID(),name:String(data.get('name')).trim(),sectorClientId:String(data.get('sector')),instructorClientId:String(data.get('instructor'))||null,iconKey:String(data.get('iconKey')),color:String(data.get('color')),enrollmentFee:Number(data.get('enrollmentFee')),settlementMode:mode,economicValue:Number(data.get('economicValue')),status:String(data.get('status')) as OnboardingActivityDraft['status']};onChange(editing?items.map(item=>item.clientId===editing.clientId?activity:item):[...items,activity]);setEditing(undefined);};
  const workerName=(id:string|null)=>{const worker=workers.find(value=>value.clientId===id);return worker?`${worker.firstName} ${worker.lastName}`:'Sin responsable';};
  return <section className="draft-editor"><h3>Actividades</h3><div className="draft-card-grid">{items.map(activity=><article className="draft-card" key={activity.clientId}><span className="draft-card__icon" aria-hidden="true">{activity.iconKey}</span><div className="draft-card__body"><strong>{activity.name}</strong><span>{workerName(activity.instructorClientId)}</span><small>{sectors.find(value=>value.clientId===activity.sectorClientId)?.name??'Sin sector'} · {activity.settlementMode==='FIXED'?'Monto fijo':'Porcentaje'} · {activity.settlementMode==='FIXED'?'$':''}{activity.economicValue}{activity.settlementMode==='VARIABLE'?'%':''}</small><small>{statusLabel[activity.status]}</small></div><div className="draft-card__actions"><button type="button" className="draft-icon-button" onClick={()=>setEditing(activity)} aria-label={`Editar ${activity.name}`}>✎</button><button type="button" className="draft-icon-button draft-icon-button--danger" onClick={()=>onChange(items.filter(value=>value.clientId!==activity.clientId))} aria-label={`Eliminar ${activity.name}`}>🗑</button></div></article>)}<button className="draft-add-card" type="button" onClick={()=>setEditing(null)}><span aria-hidden="true">＋</span><strong>Agregar Nueva Actividad</strong></button></div>
  {editing!==undefined&&<DraftEditorModal title={editing?'Editar actividad':'Agregar Nueva Actividad'} onClose={()=>setEditing(undefined)}><form className="draft-form" onSubmit={save}><label>Nombre<input name="name" required defaultValue={editing?.name}/></label><div className="draft-form__grid"><label>Responsable<select name="instructor" defaultValue={editing?.instructorClientId??''}><option value="">Sin responsable</option>{workers.filter(worker=>worker.role==='INSTRUCTOR').map(worker=><option key={worker.clientId} value={worker.clientId}>{worker.firstName} {worker.lastName}</option>)}</select></label><label>Sector<select name="sector" required defaultValue={editing?.sectorClientId??''}><option value="">Seleccionar…</option>{sectors.map(sector=><option key={sector.clientId} value={sector.clientId}>{sector.name}</option>)}</select></label><label>Modalidad<select name="settlementMode" defaultValue={editing?.settlementMode??'VARIABLE'}><option value="FIXED">Remuneración fija</option><option value="VARIABLE">Porcentaje variable</option></select></label><label>Monto / porcentaje<input name="economicValue" type="number" min="0" step="0.01" defaultValue={editing?.economicValue??0}/></label><label>Inscripción<input name="enrollmentFee" type="number" min="0" defaultValue={editing?.enrollmentFee??0}/></label><label>Color<input name="color" type="color" defaultValue={editing?.color??'#2563EB'}/></label><label>Estado<select name="status" defaultValue={editing?.status??'inactive'}><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label></div><fieldset><legend>Icono de la actividad</legend><div className="draft-icon-grid">{icons.map((icon,index)=><label key={`${icon}-${index}`}><input type="radio" name="iconKey" value={icon} defaultChecked={(editing?.iconKey??icons[0])===icon}/><span aria-hidden="true">{icon}</span><span className="sr-only">Icono {index+1}</span></label>)}</div></fieldset><footer><button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-btn" type="submit">Guardar en el borrador</button></footer></form></DraftEditorModal>}
  </section>;
}
