import { ACTIVITY_VISUAL_CATALOG, areActivitySchedulesValid, getActivityVisual, type ActivityFeeFrequency, type ActivityScheduleBlock, type OnboardingActivityDraft, type OnboardingSectorDraft, type OnboardingWorkerDraft, type OperationalCurrency } from '@miclub/shared';
import { useState, type FormEvent } from 'react';
import { DraftEditorModal } from './DraftEditorModal';
import { FormattedValueInput } from '../../shared/FormattedValueInput';
import { ActivityScheduleEditor } from '../../shared/ActivityScheduleEditor';
import { ActivityIconPicker, ConfigurationColorPicker } from '../../shared/ConfigurationVisualFields';

const frequencyLabels: Record<ActivityFeeFrequency,string> = { DAILY:'Diaria', WEEKLY:'Semanal', MONTHLY:'Mensual', YEARLY:'Anual' };
const currencySymbol = (currency: OperationalCurrency) => new Intl.NumberFormat('es-AR',{style:'currency',currency}).formatToParts(0).find(part=>part.type==='currency')?.value ?? currency;

type Props = { items: OnboardingActivityDraft[]; sectors: OnboardingSectorDraft[]; workers: OnboardingWorkerDraft[]; currency: OperationalCurrency; onChange:(items:OnboardingActivityDraft[])=>void };
type EditorProps = Omit<Props,'items'|'onChange'> & { initial: OnboardingActivityDraft | null; onSave:(value:OnboardingActivityDraft)=>void };

function ActivityEditor({ initial, sectors, workers, currency, onSave }:EditorProps) {
  const [mode,setMode]=useState<'FIXED'|'VARIABLE'>(initial?.settlementMode??'VARIABLE');
  const [generatesEnrollments,setGeneratesEnrollments]=useState<boolean|null>(initial?.generatesEnrollments??null);
  const [schedules,setSchedules]=useState<ActivityScheduleBlock[]>(initial?.schedules??[]);
  const [error,setError]=useState('');
  const [color,setColor]=useState(initial?.color??'#2563EB'); const [icon,setIcon]=useState(initial?.iconKey??ACTIVITY_VISUAL_CATALOG[0].key);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(generatesEnrollments===null)return;const data=new FormData(event.currentTarget);const field=(key:string)=>{const value=data.get(key);return typeof value==='string'?value:'';};
    const pricing={enrollmentPrice:Number(field('enrollmentPrice')),feePrice:Number(field('feePrice')),feeFrequency:field('feeFrequency') as ActivityFeeFrequency};
    if(!areActivitySchedulesValid(schedules)||![pricing.enrollmentPrice,pricing.feePrice].every(value=>Number.isSafeInteger(value)&&value>=0)||(mode==='VARIABLE'&&Number(field('clubSharePercentage'))>100)){setError('Revisá precios, porcentaje y horarios antes de guardar.');return;}
    const common={clientId:initial?.clientId??crypto.randomUUID(),name:field('name').trim(),sectorClientId:field('sector'),responsibleWorkerClientId:field('responsibleWorker'),instructorClientId:null,iconKey:icon,color,status:field('status') as 'active'|'inactive',generatesEnrollments,pricing,schedules};onSave(mode==='FIXED'?{...common,settlementMode:mode,fixedClubFee:Number(field('fixedClubFee')),fixedFeeFrequency:field('fixedFeeFrequency') as ActivityFeeFrequency,currencyCode:currency,clubSharePercentage:null}:{...common,settlementMode:mode,fixedClubFee:null,fixedFeeFrequency:null,currencyCode:null,clubSharePercentage:Number(field('clubSharePercentage'))});};
  return <form id="activity-draft-form" className="draft-form" onSubmit={submit}>
    {error&&<p className="activity-form__error" role="alert">{error}</p>}
    <div className="draft-form__grid draft-form__identity"><label>Nombre<input name="name" required defaultValue={initial?.name}/></label><label>Responsable operativo<select name="responsibleWorker" required defaultValue={initial?.responsibleWorkerClientId??initial?.instructorClientId??''}><option value="">Seleccionar…</option>{workers.map(worker=><option key={worker.clientId} value={worker.clientId}>{worker.firstName} {worker.lastName} · {worker.role}</option>)}</select></label></div>
    <fieldset><legend>Organización</legend><div className="draft-form__grid"><label>Sector<select name="sector" required defaultValue={initial?.sectorClientId??''}><option value="">Seleccionar…</option>{sectors.map(sector=><option key={sector.clientId} value={sector.clientId}>{sector.name}</option>)}</select></label><label>Estado<select name="status" defaultValue={initial?.status??'inactive'}><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label></div></fieldset>
    <fieldset><legend>Inscripciones</legend><div className="activity-terms__modes" role="radiogroup" aria-label="¿Admite inscripciones?"><label className={`activity-terms__mode${generatesEnrollments===true?' activity-terms__mode--selected':''}`}><input type="radio" name="generatesEnrollments" required checked={generatesEnrollments===true} onChange={()=>setGeneratesEnrollments(true)}/><span><strong>Sí, admite inscripciones</strong><small>La actividad podrá seleccionarse al registrar nuevos inscriptos.</small></span></label><label className={`activity-terms__mode${generatesEnrollments===false?' activity-terms__mode--selected':''}`}><input type="radio" name="generatesEnrollments" required checked={generatesEnrollments===false} onChange={()=>setGeneratesEnrollments(false)}/><span><strong>No admite inscripciones</strong><small>Conserva su historia, pero bloquea nuevas inscripciones.</small></span></label></div></fieldset>
    <fieldset><legend>Condiciones económicas</legend><div className="draft-form__grid"><label>Modalidad<select value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="VARIABLE">Porcentaje del club</option><option value="FIXED">Monto fijo para el club</option></select></label>{mode==='VARIABLE'?<label>Porcentaje del club<FormattedValueInput kind="percent" name="clubSharePercentage" required defaultValue={initial?.settlementMode==='VARIABLE'?initial.clubSharePercentage:0}/><small>El club conserva este porcentaje; el resto corresponde al responsable.</small></label>:<><label>Monto fijo para el club<FormattedValueInput kind="money" currency={currency} name="fixedClubFee" required defaultValue={initial?.settlementMode==='FIXED'?initial.fixedClubFee:0}/></label><label>Frecuencia<select name="fixedFeeFrequency" required defaultValue={initial?.settlementMode==='FIXED'?initial.fixedFeeFrequency:'MONTHLY'}>{Object.entries(frequencyLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></>}</div></fieldset>
    <fieldset><legend>Precios para alumnos</legend><div className="activity-prices__grid"><label>Inscripción<FormattedValueInput kind="money" currency={currency} name="enrollmentPrice" required defaultValue={initial?.pricing.enrollmentPrice??0}/></label><label>Cuota<FormattedValueInput kind="money" currency={currency} name="feePrice" required defaultValue={initial?.pricing.feePrice??0}/></label><label>Frecuencia<select name="feeFrequency" defaultValue={initial?.pricing.feeFrequency??'MONTHLY'}>{Object.entries(frequencyLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><small>Moneda base del club: {currency}</small></fieldset>
    <fieldset><legend>Días y horarios</legend><ActivityScheduleEditor value={schedules} onChange={setSchedules}/></fieldset>
    <ConfigurationColorPicker value={color} onChange={setColor} label="Color de la actividad"/><ActivityIconPicker value={icon} onChange={setIcon}/>
  </form>;
}

export function ActivityDraftList({ items, sectors, workers, currency, onChange }:Props) {
  const [editing,setEditing]=useState<OnboardingActivityDraft|null>(); const icon=(key:string)=>getActivityVisual(key).glyph;
  const save=(activity:OnboardingActivityDraft)=>{onChange(editing?items.map(item=>item.clientId===editing.clientId?activity:item):[...items,activity]);setEditing(undefined);};
  return <section className="draft-editor"><h3>Actividades</h3><div className="draft-card-grid">{items.map(activity=><article className="draft-card" key={activity.clientId}><span className="draft-card__icon" aria-hidden="true">{icon(activity.iconKey)}</span><div className="draft-card__body"><strong>{activity.name}</strong><span>{workers.find(value=>value.clientId===(activity.responsibleWorkerClientId??activity.instructorClientId))?.firstName??'Sin responsable operativo'}</span><small>{sectors.find(value=>value.clientId===activity.sectorClientId)?.name??'Sin sector'} · {activity.generatesEnrollments?'Admite inscripciones':'Sin inscripciones'} · {activity.settlementMode==='FIXED'?`${currencySymbol(currency)} ${activity.fixedClubFee} ${frequencyLabels[activity.fixedFeeFrequency].toLowerCase()}`:`${activity.clubSharePercentage}% para el club`}</small></div><div className="draft-card__actions"><button type="button" className="draft-icon-button" onClick={()=>setEditing(activity)} aria-label={`Editar ${activity.name}`}>✎</button><button type="button" className="draft-icon-button draft-icon-button--danger" onClick={()=>onChange(items.filter(value=>value.clientId!==activity.clientId))} aria-label={`Eliminar ${activity.name}`}>🗑</button></div></article>)}<button className="draft-add-card" type="button" onClick={()=>setEditing(null)}><span aria-hidden="true">＋</span><strong>Agregar Nueva Actividad</strong></button></div>
  {editing!==undefined&&<DraftEditorModal size="large" title={editing?'Editar actividad':'Agregar Nueva Actividad'} onClose={()=>setEditing(undefined)} footer={<><button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-btn" type="submit" form="activity-draft-form">Guardar en el borrador</button></>}><ActivityEditor initial={editing} sectors={sectors} workers={workers} currency={currency} onSave={save}/></DraftEditorModal>}</section>;
}
