import { ACTIVITY_VISUAL_CATALOG, getActivityVisual, SECTOR_COLOR_PALETTE, type ActivityFeeFrequency, type OnboardingActivityDraft, type OnboardingSectorDraft, type OnboardingWorkerDraft, type OperationalCurrency } from '@miclub/shared';
import { useState, type FormEvent } from 'react';
import { DraftEditorModal } from './DraftEditorModal';
import { MoneyInput } from '../MoneyInput';

const frequencyLabels: Record<ActivityFeeFrequency,string> = { DAILY:'Diaria', WEEKLY:'Semanal', MONTHLY:'Mensual', YEARLY:'Anual' };
const currencySymbol = (currency: OperationalCurrency) => new Intl.NumberFormat('es-AR',{style:'currency',currency}).formatToParts(0).find(part=>part.type==='currency')?.value ?? currency;

type Props = { items: OnboardingActivityDraft[]; sectors: OnboardingSectorDraft[]; workers: OnboardingWorkerDraft[]; currency: OperationalCurrency; onChange:(items:OnboardingActivityDraft[])=>void };
type EditorProps = Omit<Props,'items'|'onChange'> & { initial: OnboardingActivityDraft | null; onSave:(value:OnboardingActivityDraft)=>void };

function ColorControl({ value, onChange }:{value:string;onChange:(value:string)=>void}) {
  return <fieldset className="draft-color-control"><legend>Color de la actividad</legend><div className="draft-palette">{SECTOR_COLOR_PALETTE.map(color=><label key={color.hex} style={{backgroundColor:color.hex}} title={color.name}><input type="radio" name="activityColor" value={color.hex} checked={value.toUpperCase()===color.hex} onChange={()=>onChange(color.hex)}/><span className="sr-only">{color.name}</span></label>)}</div><label className="draft-color-control__button">Elegir color personalizado<input aria-label="Abrir selector de color personalizado" type="color" value={value} onChange={event=>onChange(event.target.value)}/></label></fieldset>;
}
function IconPicker({ value, onChange }:{value:string;onChange:(value:string)=>void}) {
  const [query,setQuery]=useState(''); const visible=ACTIVITY_VISUAL_CATALOG.filter(item=>`${item.key} ${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const categories=[...new Set(visible.map(item=>item.category))];
  return <fieldset><legend>Icono de la actividad</legend><input type="search" aria-label="Buscar iconos de actividad" placeholder="Buscar por nombre o categoría" value={query} onChange={event=>setQuery(event.target.value)}/><div className="draft-icon-catalog">{categories.map(category=><section key={category} aria-label={category}><strong>{category}</strong><div className="draft-icon-grid">{visible.filter(item=>item.category===category).map(item=><label key={item.key} title={`${item.name} · ${category}`} aria-label={`${item.name} · ${category}`}><input type="radio" name="activityIcon" checked={value===item.key} onChange={()=>onChange(item.key)}/><span aria-hidden="true">{item.glyph}</span><span className="sr-only">{item.name}</span></label>)}</div></section>)}</div></fieldset>;
}
function ActivityEditor({ initial, sectors, workers, currency, onSave }:EditorProps) {
  const [mode,setMode]=useState<'FIXED'|'VARIABLE'>(initial?.settlementMode??'VARIABLE');
  const [color,setColor]=useState(initial?.color??'#2563EB'); const [icon,setIcon]=useState(initial?.iconKey??ACTIVITY_VISUAL_CATALOG[0].key);
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const field=(key:string)=>{const value=data.get(key);return typeof value==='string'?value:'';};const common={clientId:initial?.clientId??crypto.randomUUID(),name:field('name').trim(),sectorClientId:field('sector'),instructorClientId:field('instructor')||null,iconKey:icon,color,status:field('status') as 'active'|'inactive'};onSave(mode==='FIXED'?{...common,settlementMode:mode,fixedClubFee:Number(field('fixedClubFee')),fixedFeeFrequency:field('fixedFeeFrequency') as ActivityFeeFrequency,currencyCode:currency,clubSharePercentage:null}:{...common,settlementMode:mode,fixedClubFee:null,fixedFeeFrequency:null,currencyCode:null,clubSharePercentage:Number(field('clubSharePercentage'))});};
  const money=currencySymbol(currency);
  return <form id="activity-draft-form" className="draft-form" onSubmit={submit}>
    <div className="draft-form__grid draft-form__identity"><label>Nombre<input name="name" required defaultValue={initial?.name}/></label><label>Instructor responsable<select name="instructor" required defaultValue={initial?.instructorClientId??''}><option value="">Seleccionar…</option>{workers.filter(worker=>worker.role==='INSTRUCTOR').map(worker=><option key={worker.clientId} value={worker.clientId}>{worker.firstName} {worker.lastName}</option>)}</select></label></div>
    <fieldset><legend>Organización</legend><div className="draft-form__grid"><label>Sector<select name="sector" required defaultValue={initial?.sectorClientId??''}><option value="">Seleccionar…</option>{sectors.map(sector=><option key={sector.clientId} value={sector.clientId}>{sector.name}</option>)}</select></label><label>Estado<select name="status" defaultValue={initial?.status??'inactive'}><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label></div></fieldset>
    <fieldset><legend>Condiciones económicas</legend><div className="draft-form__grid"><label>Modalidad<select value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="VARIABLE">Porcentaje del club</option><option value="FIXED">Monto fijo para el club</option></select></label>{mode==='VARIABLE'?<label>Porcentaje del club<div className="draft-input-affix draft-input-affix--suffix"><input name="clubSharePercentage" type="number" min="0" max="100" step="0.01" required defaultValue={initial?.settlementMode==='VARIABLE'?initial.clubSharePercentage:0}/><span>%</span></div><small>El club conserva este porcentaje; el resto corresponde al responsable.</small></label>:<><label>Monto fijo para el club<MoneyInput prefix={money} name="fixedClubFee" min="0" step="0.01" required defaultValue={initial?.settlementMode==='FIXED'?initial.fixedClubFee:0}/></label><label>Frecuencia<select name="fixedFeeFrequency" defaultValue={initial?.settlementMode==='FIXED'?initial.fixedFeeFrequency:'MONTHLY'}>{Object.entries(frequencyLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></>}</div></fieldset>
    <div className="draft-form__grid"><ColorControl value={color} onChange={setColor}/></div><IconPicker value={icon} onChange={setIcon}/>
  </form>;
}

export function ActivityDraftList({ items, sectors, workers, currency, onChange }:Props) {
  const [editing,setEditing]=useState<OnboardingActivityDraft|null>(); const icon=(key:string)=>getActivityVisual(key).glyph;
  const save=(activity:OnboardingActivityDraft)=>{onChange(editing?items.map(item=>item.clientId===editing.clientId?activity:item):[...items,activity]);setEditing(undefined);};
  return <section className="draft-editor"><h3>Actividades</h3><div className="draft-card-grid">{items.map(activity=><article className="draft-card" key={activity.clientId}><span className="draft-card__icon" aria-hidden="true">{icon(activity.iconKey)}</span><div className="draft-card__body"><strong>{activity.name}</strong><span>{workers.find(value=>value.clientId===activity.instructorClientId)?.firstName??'Sin instructor responsable'}</span><small>{sectors.find(value=>value.clientId===activity.sectorClientId)?.name??'Sin sector'} · {activity.settlementMode==='FIXED'?`${currencySymbol(currency)} ${activity.fixedClubFee} ${frequencyLabels[activity.fixedFeeFrequency].toLowerCase()}`:`${activity.clubSharePercentage}% para el club`}</small></div><div className="draft-card__actions"><button type="button" className="draft-icon-button" onClick={()=>setEditing(activity)} aria-label={`Editar ${activity.name}`}>✎</button><button type="button" className="draft-icon-button draft-icon-button--danger" onClick={()=>onChange(items.filter(value=>value.clientId!==activity.clientId))} aria-label={`Eliminar ${activity.name}`}>🗑</button></div></article>)}<button className="draft-add-card" type="button" onClick={()=>setEditing(null)}><span aria-hidden="true">＋</span><strong>Agregar Nueva Actividad</strong></button></div>
  {editing!==undefined&&<DraftEditorModal size="large" title={editing?'Editar actividad':'Agregar Nueva Actividad'} onClose={()=>setEditing(undefined)} footer={<><button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button><button className="primary-btn" type="submit" form="activity-draft-form">Guardar en el borrador</button></>}><ActivityEditor initial={editing} sectors={sectors} workers={workers} currency={currency} onSave={save}/></DraftEditorModal>}</section>;
}
