import type { OnboardingActivityDraft, OnboardingWorkerDraft, OperationalCurrency } from '@miclub/shared';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { deleteOnboardingPhoto, uploadOnboardingPhoto } from '../../../services/api/onboardingApi';
import { getCurrencyPrefix } from '../currencyPresentation';
import { MoneyInput } from '../MoneyInput';
import { DraftEditorModal } from './DraftEditorModal';
import { activitiesForInstructor } from './draftDependencies';
import { validateWorkerPhoto } from '../../shared/workerPhotoValidation';

export { WORKER_PHOTO_MAX_BYTES, validateWorkerPhoto } from '../../shared/workerPhotoValidation';

type FixedCompensationFieldsProps = { currency:OperationalCurrency; worker:OnboardingWorkerDraft|null };
export function FixedCompensationFields({currency,worker}:FixedCompensationFieldsProps){const prefix=getCurrencyPrefix(currency);return <div className="worker-compensation-fields"><label>Monto ({currency})<MoneyInput prefix={prefix} name="fixedCompensationAmount" min="0" step="0.01" required defaultValue={worker?.hasFixedCompensation?worker.fixedCompensationAmount??0:0} aria-label={`Monto de remuneración fija en ${currency}`} /></label><label>Frecuencia<select name="fixedCompensationFrequency" required defaultValue={worker?.hasFixedCompensation?worker.fixedCompensationFrequency??'MONTHLY':'MONTHLY'}><option value="DAILY">Diaria</option><option value="WEEKLY">Semanal</option><option value="MONTHLY">Mensual</option><option value="YEARLY">Anual</option></select></label></div>}

export function WorkerDraftList({items,activities=[],onChange,currency='ARS'}:{items:OnboardingWorkerDraft[];activities?:readonly OnboardingActivityDraft[];onChange:(items:OnboardingWorkerDraft[])=>void;currency?:OperationalCurrency}){
 const [editing,setEditing]=useState<OnboardingWorkerDraft|null>();const [hasFixedCompensation,setHasFixedCompensation]=useState(false);const [photoPreview,setPhotoPreview]=useState<string|null>(null);const previewRef=useRef<string|null>(null);const [photoFileId,setPhotoFileId]=useState<string|null>(null);const [photoError,setPhotoError]=useState<string|null>(null);const [photoBusy,setPhotoBusy]=useState(false);
 const revokePreview=()=>{if(previewRef.current){URL.revokeObjectURL(previewRef.current);previewRef.current=null;}setPhotoPreview(null);};
 useEffect(()=>()=>{if(previewRef.current)URL.revokeObjectURL(previewRef.current);},[]);
 const open=(worker:OnboardingWorkerDraft|null)=>{revokePreview();setPhotoError(null);setPhotoFileId(worker?.photoFileId??null);setHasFixedCompensation(worker?.hasFixedCompensation??false);setEditing(worker);};
 const discardTemporaryPhoto=(id:string|null)=>{if(id&&id!==editing?.photoFileId)void deleteOnboardingPhoto(id).catch(()=>undefined);};
 const cancel=()=>{discardTemporaryPhoto(photoFileId);revokePreview();setEditing(undefined);};
 const removePhoto=()=>{discardTemporaryPhoto(photoFileId);revokePreview();setPhotoFileId(null);setPhotoError(null);};
 const choosePhoto=async(file?:File)=>{if(!file)return;const error=validateWorkerPhoto(file);if(error){setPhotoError(error);return;}setPhotoBusy(true);setPhotoError(null);try{const uploaded=await uploadOnboardingPhoto(file);discardTemporaryPhoto(photoFileId);revokePreview();const url=URL.createObjectURL(file);previewRef.current=url;setPhotoPreview(url);setPhotoFileId(uploaded.fileId);}catch(error){setPhotoError(error instanceof Error?error.message:'No se pudo subir la foto.');}finally{setPhotoBusy(false);}};
 const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget),get=(key:string)=>{const value=data.get(key);return typeof value==='string'?value.trim():'';};const worker:OnboardingWorkerDraft={clientId:editing?.clientId??crypto.randomUUID(),firstName:get('firstName'),lastName:get('lastName'),dni:get('dni'),phone:get('phone')||null,email:get('email')||null,password:get('password')||editing?.password,role:get('role') as OnboardingWorkerDraft['role'],photoFileId,hasFixedCompensation,fixedCompensationAmount:hasFixedCompensation?Number(data.get('fixedCompensationAmount')):null,fixedCompensationFrequency:hasFixedCompensation?get('fixedCompensationFrequency') as OnboardingWorkerDraft['fixedCompensationFrequency']:null,currencyCode:hasFixedCompensation?currency:null};onChange(editing?items.map(item=>item.clientId===editing.clientId?worker:item):[...items,worker]);if(editing?.photoFileId&&editing.photoFileId!==photoFileId)void deleteOnboardingPhoto(editing.photoFileId).catch(()=>undefined);revokePreview();setEditing(undefined);};
 return <section className="draft-editor"><h3>Trabajadores e instructores</h3><div className="draft-card-grid">{items.map(worker=>{const director=worker.role==='DIRECTOR';const linked=activitiesForInstructor(activities,worker.clientId);return <article className="draft-card" key={worker.clientId}><span className="draft-avatar" aria-hidden="true">{worker.firstName.charAt(0)}{worker.lastName.charAt(0)}</span><div className="draft-card__body"><strong>{worker.firstName} {worker.lastName}</strong><span>{worker.role==='INSTRUCTOR'?'Instructor':director?'Director':'Trabajador'}</span><small>{worker.email||worker.phone||`DNI ${worker.dni}`}</small>{director&&<small>Cuenta del sistema · protegida</small>}{linked.length>0&&<small>Responsable de {linked.map(activity=>activity.name).join(', ')}. Reasigná o eliminá la actividad primero.</small>}</div><div className="draft-card__actions">{director?<span className="draft-lock" title="El Director no se puede modificar">🔒</span>:<><button type="button" className="draft-icon-button" onClick={()=>open(worker)} aria-label={`Editar a ${worker.firstName} ${worker.lastName}`}>✎</button><button type="button" className="draft-icon-button draft-icon-button--danger" disabled={linked.length>0} onClick={()=>{if(worker.photoFileId)void deleteOnboardingPhoto(worker.photoFileId).catch(()=>undefined);onChange(items.filter(item=>item.clientId!==worker.clientId));}} aria-label={`Eliminar a ${worker.firstName} ${worker.lastName}`}>🗑</button></>}</div></article>})}<button className="draft-add-card" type="button" onClick={()=>open(null)}><span aria-hidden="true">＋</span><strong>Agregar Nuevo Trabajador/Instructor</strong></button></div>
 {editing!==undefined&&<DraftEditorModal title={editing?'Editar trabajador o instructor':'Agregar Nuevo Trabajador/Instructor'} onClose={cancel}><form className="draft-form" onSubmit={save}><section className="draft-photo" aria-labelledby="worker-photo-title"><div className="draft-photo__avatar">{photoPreview?<img src={photoPreview} alt="Foto seleccionada del trabajador"/>:<span aria-hidden="true">{(editing?.firstName?.[0]??'?')+(editing?.lastName?.[0]??'')}</span>}</div><div className="draft-photo__content"><strong id="worker-photo-title">Foto de perfil</strong><div className="draft-photo__actions"><label className="draft-photo__select">{photoBusy?'Subiendo…':'Seleccionar foto'}<input className="draft-photo__input" type="file" accept="image/jpeg,image/png,image/webp" disabled={photoBusy} onChange={event=>void choosePhoto(event.target.files?.[0])}/></label>{photoFileId&&<button type="button" className="draft-photo__remove" onClick={removePhoto} disabled={photoBusy}>Eliminar</button>}</div>{photoError&&<small className="draft-photo__message" role="alert">{photoError}</small>}</div></section><div className="draft-form__grid"><label>Nombre<input name="firstName" required defaultValue={editing?.firstName}/></label><label>Apellido<input name="lastName" required defaultValue={editing?.lastName}/></label><label>DNI<input name="dni" inputMode="numeric" pattern="[0-9]{7,9}" required defaultValue={editing?.dni}/></label><label>Teléfono<input name="phone" type="tel" defaultValue={editing?.phone??''}/></label><label>Correo electrónico<input name="email" type="email" required defaultValue={editing?.email??''}/></label><label>Rol<select name="role" defaultValue={editing?.role??'TRABAJADOR'}><option value="TRABAJADOR" disabled={Boolean(editing&&activitiesForInstructor(activities,editing.clientId).length)}>Trabajador</option><option value="INSTRUCTOR">Instructor</option></select>{editing&&activitiesForInstructor(activities,editing.clientId).length>0&&<small>Reasigná sus actividades antes de cambiar el rol.</small>}</label><label>Contraseña {editing&&<small>(dejar vacía para conservar)</small>}<input name="password" type="password" minLength={10} required={!editing} autoComplete="new-password"/></label><label className="worker-compensation-toggle"><input type="checkbox" checked={hasFixedCompensation} onChange={event=>setHasFixedCompensation(event.target.checked)}/><span>Tiene remuneración fija</span></label>{hasFixedCompensation&&<FixedCompensationFields currency={currency} worker={editing}/>}</div><footer><button type="button" onClick={cancel}>Cancelar</button><button className="primary-btn" type="submit" disabled={photoBusy}>Guardar en el borrador</button></footer></form></DraftEditorModal>}
 </section>;
}
