import type { OnboardingWorkerDraft } from '@miclub/shared';
import { useState, type FormEvent } from 'react';
import { DraftEditorModal } from './DraftEditorModal';

export function WorkerDraftList({ items, onChange }: { items: OnboardingWorkerDraft[]; onChange: (items: OnboardingWorkerDraft[]) => void }) {
  const [editing, setEditing] = useState<OnboardingWorkerDraft | null>();
  const save = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget); const get = (key:string) => String(data.get(key) ?? '').trim();
    const paymentMode = get('paymentMode') as OnboardingWorkerDraft['paymentMode'];
    const worker: OnboardingWorkerDraft = { clientId: editing?.clientId ?? crypto.randomUUID(), firstName:get('firstName'), lastName:get('lastName'), dni:get('dni'), phone:get('phone') || null, email:get('email') || null, password:get('password') || editing?.password, role:get('role') as OnboardingWorkerDraft['role'], paymentMode, monthlyFixedAmount:paymentMode === 'FIXED' ? Number(data.get('monthlyFixedAmount')) : null };
    onChange(editing ? items.map(item => item.clientId === editing.clientId ? worker : item) : [...items, worker]); setEditing(undefined);
  };
  return <section className="draft-editor"><h3>Trabajadores e instructores</h3><div className="draft-card-grid">{items.map(worker => { const director = worker.role === 'DIRECTOR'; return <article className="draft-card" key={worker.clientId}>
    <span className="draft-avatar" aria-hidden="true">{worker.firstName.charAt(0)}{worker.lastName.charAt(0)}</span><div className="draft-card__body"><strong>{worker.firstName} {worker.lastName}</strong><span>{worker.role === 'INSTRUCTOR' ? 'Instructor' : worker.role === 'DIRECTOR' ? 'Director' : 'Trabajador'}</span><small>{worker.email || worker.phone || `DNI ${worker.dni}`}</small>{director && <small>Cuenta del sistema · protegida</small>}</div>
    <div className="draft-card__actions">{director ? <span className="draft-lock" title="El Director no se puede modificar">🔒</span> : <><button type="button" className="draft-icon-button" onClick={() => setEditing(worker)} aria-label={`Editar a ${worker.firstName} ${worker.lastName}`}>✎</button><button type="button" className="draft-icon-button draft-icon-button--danger" onClick={() => onChange(items.filter(item => item.clientId !== worker.clientId))} aria-label={`Eliminar a ${worker.firstName} ${worker.lastName}`}>🗑</button></>}</div>
  </article>; })}<button className="draft-add-card" type="button" onClick={() => setEditing(null)}><span aria-hidden="true">＋</span><strong>Agregar Nuevo Trabajador/Instructor</strong></button></div>
  {editing !== undefined && <DraftEditorModal title={editing ? 'Editar trabajador o instructor' : 'Agregar Nuevo Trabajador/Instructor'} onClose={() => setEditing(undefined)}><form className="draft-form" onSubmit={save}>
    <div className="draft-photo" aria-hidden="true">📷</div><div className="draft-form__grid"><label>Nombre<input name="firstName" required defaultValue={editing?.firstName}/></label><label>Apellido<input name="lastName" required defaultValue={editing?.lastName}/></label><label>DNI<input name="dni" inputMode="numeric" pattern="[0-9]{7,9}" required defaultValue={editing?.dni}/></label><label>Teléfono<input name="phone" type="tel" defaultValue={editing?.phone ?? ''}/></label><label>Correo electrónico<input name="email" type="email" defaultValue={editing?.email ?? ''}/></label><label>Rol<select name="role" defaultValue={editing?.role ?? 'TRABAJADOR'}><option value="TRABAJADOR">Trabajador</option><option value="INSTRUCTOR">Instructor</option></select></label><label>Contraseña {editing && <small>(dejar vacía para conservar)</small>}<input name="password" type="password" minLength={10} required={!editing} autoComplete="new-password"/></label><label>Remuneración<select name="paymentMode" defaultValue={editing?.paymentMode ?? 'VARIABLE'}><option value="FIXED">Fija</option><option value="VARIABLE">Variable</option></select></label><label>Monto fijo mensual<input name="monthlyFixedAmount" type="number" min="0" defaultValue={editing?.monthlyFixedAmount ?? 0}/></label></div>
    <footer><button type="button" onClick={() => setEditing(undefined)}>Cancelar</button><button className="primary-btn" type="submit">Guardar en el borrador</button></footer></form></DraftEditorModal>}
  </section>;
}
