import { useEffect, useId, useRef, useState } from 'react';
import { useDataMigration } from './DataMigration/useDataMigration';
import { UiAlert, UiButton, UiCard, UiState, UiTable } from './shared/Ui';

const focusable = 'button:not([disabled]),[href],input:not([disabled]),[tabindex]:not([tabindex="-1"])';
const fileSize = (bytes: number) => new Intl.NumberFormat('es-AR', { style: 'unit', unit: bytes >= 1_000_000 ? 'megabyte' : 'kilobyte', maximumFractionDigits: 1 }).format(bytes / (bytes >= 1_000_000 ? 1_000_000 : 1_000));

function ConfirmApply({ onCancel, onConfirm }: { onCancel:()=>void; onConfirm:()=>void }) {
  const titleId=useId(), ref=useRef<HTMLDivElement>(null), confirmRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const prior=document.activeElement as HTMLElement|null;confirmRef.current?.focus();const listener=(event:KeyboardEvent)=>{if(event.key==='Escape')onCancel();if(event.key!=='Tab'||!ref.current)return;const nodes=[...ref.current.querySelectorAll<HTMLElement>(focusable)];if(event.shiftKey&&document.activeElement===nodes[0]){event.preventDefault();nodes.at(-1)?.focus();}else if(!event.shiftKey&&document.activeElement===nodes.at(-1)){event.preventDefault();nodes[0]?.focus();}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);prior?.focus();};},[onCancel]);
  return <div className="ui-dialog-backdrop"><div ref={ref} className="ui-dialog" role="alertdialog" aria-modal="true" aria-labelledby={titleId}><h2 id={titleId}>¿Aplicar el lote validado?</h2><p>Esta acción escribirá los cambios proyectados y no debe cerrarse durante el proceso.</p><div className="button-row"><UiButton variant="secondary" onClick={onCancel}>Cancelar</UiButton><UiButton ref={confirmRef} onClick={onConfirm}>Sí, aplicar lote</UiButton></div></div></div>;
}

export default function DataMigrationModule(){
 const state=useDataMigration(), [confirming,setConfirming]=useState(false); const valid=state.summary?.dryRun&&state.summary.errors.every(error=>error.severity!=='error'); const total=state.summary?Object.values(state.summary.rowCounts).reduce((a,b)=>a+b,0):0;
 const apply=()=>{setConfirming(false);void state.run(state.summary?.batchId);};
 return <main className="module-page migration-page"><header className="module-header"><div><p className="eyebrow">MIGRACIÓN SEGURA · DESPUÉS DEL ONBOARDING</p><h1>Importar desde XLSX</h1><p>Cargá la plantilla, revisá el dry-run y confirmá el lote antes de escribir datos.</p></div><UiButton variant="secondary" onClick={()=>void state.downloadTemplate()}>Descargar plantilla XLSX</UiButton></header>
 <UiCard className="migration-upload"><h2>1. Elegir archivo y validar</h2><label className="migration-dropzone"><strong>Seleccionar archivo XLSX</strong><span>Arrastrá un archivo aquí o activá este control. Máximo según la configuración del servidor.</span><input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={event=>state.setFile(event.target.files?.[0])}/></label>
 {state.file&&<div className="migration-file" role="status"><span aria-hidden="true">📄</span><div><strong>{state.file.name}</strong><small>{fileSize(state.file.size)}</small></div><UiButton variant="secondary" disabled={state.loading} onClick={()=>state.setFile(undefined)}>Quitar</UiButton></div>}
 {state.loading&&<div className="migration-progress" aria-live="polite"><label htmlFor="migration-progress">{state.summary?.dryRun?'Aplicando':'Cargando y validando'}: {state.progress}%</label><progress id="migration-progress" max="100" value={state.progress}/></div>}
 <div className="button-row"><UiButton disabled={!state.file||state.loading} onClick={()=>void state.run()}>Ejecutar dry-run</UiButton>{valid&&<UiButton disabled={state.loading} onClick={()=>setConfirming(true)}>Aplicar este dry-run</UiButton>}</div>{state.message&&<UiAlert tone="error">{state.message}</UiAlert>}</UiCard>
 {state.summary&&<UiCard><h2>{state.summary.dryRun?'2. Resumen del dry-run':'3. Resultado final'}</h2><div className="migration-result" aria-live="polite"><UiAlert tone={state.summary.errors.some(e=>e.severity==='error')?'error':state.summary.dryRun?'warning':'success'}><strong>{state.summary.dryRun?(valid?'Validación lista para confirmar':'Validación con errores'):'Migración aplicada'}</strong><span>{total} filas · {state.summary.projectedWrites.total} escrituras {state.summary.dryRun?'proyectadas':'procesadas'}</span></UiAlert></div><dl className="migration-summary-grid"><div><dt>Lote XLSX</dt><dd>{state.summary.batchId}</dd></div><div><dt>Versión</dt><dd>{state.summary.templateVersion}</dd></div><div><dt>Filas</dt><dd>{total}</dd></div><div><dt>Escrituras proyectadas</dt><dd>{state.summary.projectedWrites.total}</dd></div></dl></UiCard>}
 <UiCard><h2>Errores por fila</h2>{state.errors.length===0?<UiState title="Sin errores registrados"><p>Los problemas de validación aparecerán aquí.</p></UiState>:<UiTable label="Errores de migración; desplazable horizontalmente"><thead><tr><th>Severidad</th><th>Código</th><th>Hoja</th><th>Fila</th><th>Campo</th><th>Valor normalizado</th><th>Mensaje</th></tr></thead><tbody>{state.errors.map((error,index)=><tr key={`${error.error_code}-${index}`}><td>{error.severity}</td><td>{error.error_code}</td><td>{error.sheet??'—'}</td><td>{error.row_number??'—'}</td><td>{error.field??'—'}</td><td>{error.value_normalized??'—'}</td><td>{error.message}</td></tr>)}</tbody></UiTable>}</UiCard><UiAlert tone="warning">Cada aplicación requiere un dry-run válido del mismo lote XLSX.</UiAlert>{confirming&&<ConfirmApply onCancel={()=>setConfirming(false)} onConfirm={apply}/>}</main>;
}
