import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { HomeAlerts } from './Home/HomeAlerts';
import { HomeMetricCards } from './Home/HomeMetricCards';
import { RecentMovements } from './Home/RecentMovements';
import { SectorDistribution } from './Home/SectorDistribution';
import { useHomeDashboard } from './Home/useHomeDashboard';
export default function HomeModule({ onOpenModule }) {
    const dashboard = useHomeDashboard();
    return (_jsxs("main", { className: "module-content", children: [_jsxs("section", { className: "module-hero home-hero", children: [_jsxs("div", { className: "home-hero__copy", children: [_jsx("p", { className: "eyebrow", children: "Inicio" }), _jsx("h2", { children: "Panel operativo de miClub" }), _jsx("p", { children: "Resumen ejecutivo e indicadores generales." })] }), _jsxs("div", { className: "home-sync-badges", "aria-label": "Sincronizaci\u00F3n del inicio", children: [_jsx("span", { className: dashboard.syncStatus?.error ? 'home-sync-badge hero-sync-badge--compact home-sync-badge--warning' : 'home-sync-badge hero-sync-badge--compact', title: dashboard.syncStatus?.error, children: dashboard.syncBadgeLabel }), _jsx("span", { className: "home-sync-badge hero-sync-badge--compact home-sync-badge--muted", children: dashboard.lastSyncLabel }), _jsx("button", { className: "icon-btn home-sync-button", onClick: () => void dashboard.loadHome(), disabled: dashboard.loading, children: "Sincronizar" })] })] }), _jsx(HomeAlerts, { error: dashboard.error, loading: dashboard.loading }), _jsxs("section", { className: "home-dashboard-stack", "aria-label": "Resumen operativo del club", children: [_jsx(HomeMetricCards, { financialSummaryLines: dashboard.financialSummaryLines, operationalBalanceLines: dashboard.operationalBalanceLines, incomeBySectorLines: dashboard.incomeBySectorLines, expenseBySectorLines: dashboard.expenseBySectorLines, financeError: dashboard.financeError, financeSummary: dashboard.financeSummary }), _jsx(RecentMovements, { enrollmentStats: dashboard.enrollmentStats, weightedAverageFeeLabel: dashboard.weightedAverageFeeLabel, mainDebtorBreakdown: dashboard.mainDebtorBreakdown, remainingDebtorActivities: dashboard.remainingDebtorActivities, totalDebtors: dashboard.totalDebtors, maxDebtorActivityCount: dashboard.maxDebtorActivityCount, mainActiveActivityBreakdown: dashboard.mainActiveActivityBreakdown, remainingActiveActivities: dashboard.remainingActiveActivities, maxActiveActivityCount: dashboard.maxActiveActivityCount })] }), _jsx(SectorDistribution, { sectorError: dashboard.sectorError, sectorCards: dashboard.sectorCards, loadHome: dashboard.loadHome, onOpenModule: onOpenModule })] }));
}
