import { getActivityVisual, type AdministrationActivityDto, type AdministrationEnrollmentDto, type AdministrationMovementDto } from '@miclub/shared';
import { useEffect, useState, type CSSProperties } from 'react';
import { getActivityEnrollments, getActivityMovements, getActivityPriceHistory, getActivityTermHistory, type ActivityPriceHistoryItem, type ActivityTermHistoryItem } from '../../services/api/administrationApi';
import { ConfigurationEditorModal } from '../shared/ConfigurationEditorModal';
import { describeSchedule } from '../shared/ActivityScheduleEditor';
import { activityStatusLabel, describeActivityTerms, formatActivityDate, formatActivityProfitability, formatFrequency, formatMoney, formatPercentage } from './activityPresentation';

type Props = {
  activity: AdministrationActivityDto; canEdit: boolean; canArchive: boolean; canViewFinancials: boolean; canViewEnrollments: boolean; busy: boolean;
  onClose: () => void; onEdit: () => void; onStatus: () => Promise<void>; onArchive: () => Promise<void>;
};
const displayStatus = (value?: string | null) => value?.replaceAll('_', ' ').toLocaleLowerCase('es-AR') || 'Sin estado';
const termValue=(term:ActivityTermHistoryItem)=>term.mode==='FIXED'?`${formatMoney(term.fixedClubFee??0,term.currencyCode??'ARS')} · ${formatFrequency(term.fixedFeeFrequency)}`:`${formatPercentage(term.clubSharePercentage??0)} para el club`;

export function ActivityDetailModal({ activity, canEdit, canArchive, canViewFinancials, canViewEnrollments, busy, onClose, onEdit, onStatus, onArchive }: Props) {
  const [enrollments, setEnrollments] = useState<AdministrationEnrollmentDto[]>([]);
  const [movements, setMovements] = useState<AdministrationMovementDto[]>([]);
  const [terms,setTerms]=useState<ActivityTermHistoryItem[]>([]);
  const [prices,setPrices]=useState<ActivityPriceHistoryItem[]>([]);
  const [loadState,setLoadState]=useState({enrollments:'loading',movements:'loading',terms:'loading'} as Record<'enrollments'|'movements'|'terms','loading'|'ready'|'error'>);
  const [loadErrors,setLoadErrors]=useState<Partial<Record<'enrollments'|'movements'|'terms',string>>>({});
  const [actionError, setActionError] = useState<string | null>(null);
  const visual=getActivityVisual(activity.iconKey);
  const color=activity.color||'#2563EB';
  const futureTerms=terms.filter(term=>term.phase==='FUTURE');
  const pastAndCurrentTerms=terms.filter(term=>term.phase!=='FUTURE');

  useEffect(() => {
    const controller = new AbortController();
    const loadPart=<K extends 'enrollments'|'movements'|'terms'>(key:K,request:Promise<{items:K extends 'enrollments'?AdministrationEnrollmentDto[]:K extends 'movements'?AdministrationMovementDto[]:ActivityTermHistoryItem[]}>,save:(items:never[])=>void)=>request.then(response=>{if(!controller.signal.aborted){save(response.items as never[]);setLoadState(current=>({...current,[key]:'ready'}));}}).catch(reason=>{if(!controller.signal.aborted){setLoadState(current=>({...current,[key]:'error'}));setLoadErrors(current=>({...current,[key]:reason instanceof Error?reason.message:'No se pudo cargar esta sección.'}));}});
    if (canViewEnrollments) void loadPart('enrollments',getActivityEnrollments(activity.id,controller.signal),items=>setEnrollments(items as AdministrationEnrollmentDto[]));
    if (canViewFinancials) void loadPart('movements',getActivityMovements(activity.id,controller.signal),items=>setMovements(items as AdministrationMovementDto[]));
    void loadPart('terms',getActivityTermHistory(activity.id,controller.signal),items=>setTerms(items as ActivityTermHistoryItem[]));
    void getActivityPriceHistory(activity.id,controller.signal).then(response=>{if(!controller.signal.aborted)setPrices(response.items);}).catch(()=>undefined);
    return () => controller.abort();
  }, [activity.id, canViewEnrollments, canViewFinancials]);

  const run=async(action:()=>Promise<void>)=>{setActionError(null);try{await action();}catch(reason){setActionError(reason instanceof Error?reason.message:'No se pudo modificar la actividad.');}};
  return <ConfigurationEditorModal size="large" eyebrow="Ficha de actividad" title={activity.name} description="Resumen operativo, económico y trazabilidad de la actividad." busy={busy} onClose={onClose}
    footer={<>{canArchive&&<button className="danger-btn activity-detail__archive" type="button" disabled={busy} onClick={()=>void run(onArchive)}>Archivar actividad</button>}<button className="ghost-btn" type="button" disabled={busy} onClick={onClose}>Cerrar</button>{canEdit&&<button className="ghost-btn" type="button" disabled={busy} onClick={()=>void run(onStatus)}>{activity.status==='active'?'Desactivar':'Activar'}</button>}{canEdit&&<button className="primary-btn" type="button" disabled={busy} onClick={onEdit}>Editar actividad</button>}</>}>
    <div className="activity-detail"><div className="activity-detail__hero" style={{'--activity-color':color} as CSSProperties}><span className="activity-detail__icon" aria-hidden="true">{visual.glyph}</span><div><strong>{activity.name}</strong><span>{activity.modality||'Sin modalidad operativa'} · {activity.sectorName||'Sin sector'}</span></div><span className="activity-list__status" data-active={activity.status==='active'}>{activityStatusLabel(activity.status)}</span></div>
    <section className="activity-detail__summary" aria-label="Resumen de actividad"><div><small>Responsable operativo</small><strong>{activity.responsibleEmployeeName||activity.instructorName||'Sin asignar'}</strong></div><div><small>Receptor económico</small><strong>{activity.responsiblePersonName||activity.responsibleEmployeeName||'Sin asignar'}</strong></div><div><small>Inscripciones</small><strong>{activity.generatesEnrollments?'Habilitadas':'No habilitadas'}</strong><span>{activity.currentEnrollments??0} activas</span></div>{canViewFinancials&&<div><small>Rentabilidad operativa {activity.annualOperatingProfitabilityYear??''}</small><strong data-negative={(activity.annualOperatingProfitability??0)<0}>{formatActivityProfitability(activity)}</strong><span>{activity.annualOperatingMovements??0} movimientos</span></div>}<div><small>Color</small><strong className="activity-detail__color"><i style={{backgroundColor:color}}/>{color.toUpperCase()}</strong></div></section>
    <section className="activity-detail__terms"><div><p className="eyebrow">Condiciones vigentes</p><h4>{describeActivityTerms(activity)}</h4><span>{activity.termsEffectiveFrom?`Desde ${formatActivityDate(activity.termsEffectiveFrom)}`:'Sin vigencia actual'}{activity.termsEffectiveTo?` hasta ${formatActivityDate(activity.termsEffectiveTo)}`:''}</span></div><div><small>Modalidad</small><strong>{activity.settlementMode?.toUpperCase()==='FIXED'?'Monto fijo':'Porcentaje del club'}</strong></div></section>
    <section className="activity-detail__section"><header><div><h4>Precios para alumnos</h4><p>Inscripción y cuota vigentes en moneda base del club.</p></div></header>{activity.pricingConfigured?<div className="activity-detail__price-grid"><div><small>Inscripción</small><strong>{formatMoney(activity.enrollmentPrice??0,activity.priceCurrencyCode??activity.operatingCurrencyCode)}</strong></div><div><small>Cuota</small><strong>{formatMoney(activity.feePrice??0,activity.priceCurrencyCode??activity.operatingCurrencyCode)} · {formatFrequency(activity.feeFrequency)}</strong></div></div>:<p className="activity-detail__empty">Sin configurar</p>}{prices.length>0&&<ol className="activity-detail__timeline" aria-label="Historial de precios">{prices.map(price=><li key={price.id}><i/><div><strong>Inscripción {formatMoney(price.enrollmentPrice,price.currencyCode)} · Cuota {formatMoney(price.feePrice,price.currencyCode)} {formatFrequency(price.feeFrequency)}</strong><small>Desde {formatActivityDate(price.effectiveFrom)}{price.effectiveTo?` hasta ${formatActivityDate(price.effectiveTo)}`:''}</small></div><span>{price.cancelledAt?'Cancelada':'Registrada'}</span></li>)}</ol>}</section>
    <section className="activity-detail__section"><header><div><h4>Días y horarios</h4><p>Horarios semanales en la zona horaria del club.</p></div><span>{activity.schedules.length}</span></header>{activity.schedules.length?<ul className="activity-detail__schedule">{activity.schedules.map(block=><li key={block.id}>{describeSchedule(block)}</li>)}</ul>:<p className="activity-detail__empty">Sin horarios configurados.</p>}</section>
    {loadState.terms==='ready'&&futureTerms.length>0&&<section className="activity-detail__section activity-detail__section--future"><header><div><h4>Próximas vigencias</h4><p>Cambios programados que todavía no están activos.</p></div><span>{futureTerms.length}</span></header><ol className="activity-detail__timeline">{futureTerms.map(term=><li key={term.id}><i/><div><strong>{termValue(term)}</strong><small>Desde {formatActivityDate(term.effectiveFrom)} · {term.responsiblePersonName||'receptor automático'}</small></div><span>v{term.revision}</span></li>)}</ol></section>}
    <section className="activity-detail__section"><header><div><h4>Historia económica</h4><p>La condición vigente y las versiones anteriores permanecen intactas.</p></div><span>{pastAndCurrentTerms.length}</span></header>{loadState.terms==='loading'?<p role="status">Cargando vigencias…</p>:loadState.terms==='error'?<p className="activity-form__error" role="alert">{loadErrors.terms}</p>:pastAndCurrentTerms.length?<ol className="activity-detail__timeline">{pastAndCurrentTerms.map(term=><li key={term.id} data-current={term.phase==='CURRENT'}><i/><div><strong>{termValue(term)}</strong><small>{formatActivityDate(term.effectiveFrom)} — {term.effectiveTo?formatActivityDate(term.effectiveTo):'vigente'} · {term.responsiblePersonName||'receptor automático'}</small></div><span>v{term.revision}</span></li>)}</ol>:<p className="activity-detail__empty">No hay términos económicos disponibles.</p>}</section>
    <div className="activity-detail__related">{canViewEnrollments&&<section className="activity-detail__section"><header><div><h4>Inscriptos</h4><p>Personas vinculadas a la actividad.</p></div><span>{enrollments.length}</span></header>{loadState.enrollments==='loading'?<p role="status">Cargando inscriptos…</p>:loadState.enrollments==='error'?<p className="activity-form__error" role="alert">{loadErrors.enrollments}</p>:enrollments.length?<ul className="sector-modal__items">{enrollments.map(item=><li key={item.id}><div><strong>{item.displayName||`${item.firstName||''} ${item.lastName||''}`.trim()||'Persona sin nombre'}</strong><small>{displayStatus(item.status)} · vence {item.dueDate?formatActivityDate(item.dueDate):'sin fecha'}</small></div><span>{formatMoney(item.feeAmount)}</span></li>)}</ul>:<p className="activity-detail__empty">No hay inscriptos asociados.</p>}</section>}
      {canViewFinancials&&<section className="activity-detail__section"><header><div><h4>Movimientos asociados</h4><p>Impacto financiero directo.</p></div><span>{movements.length}</span></header>{loadState.movements==='loading'?<p role="status">Cargando movimientos…</p>:loadState.movements==='error'?<p className="activity-form__error" role="alert">{loadErrors.movements}</p>:movements.length?<ul className="sector-modal__items">{movements.map(item=><li key={item.id}><div><strong>{item.concept||item.category||'Sin concepto'}</strong><small>{formatActivityDate(item.date)} · {displayStatus(item.status)}</small></div><span className={item.type==='EGRESOS'?'sector-modal__amount--expense':''}>{formatMoney(item.amount)}</span></li>)}</ul>:<p className="activity-detail__empty">No hay movimientos asociados.</p>}</section>}</div>
    <section className="activity-detail__audit"><small>Creada {formatActivityDate(activity.createdAt)}</small><small>Actualizada {formatActivityDate(activity.updatedAt)}</small><code>{activity.id}</code></section>
    {actionError&&<p className="activity-form__error" role="alert">{actionError}</p>}</div>
  </ConfigurationEditorModal>;
}
