import { useEffect, useRef, useState, type FormEvent } from 'react';
import { PERMISSIONS } from '@miclub/shared';
import { createAdministrationEnrollment, getEnrollmentFormCatalogs, getMovementFormCatalogs, getEnrollmentPricePreview, type EnrollmentPerson, type EnrollmentCatalogItem, type EnrollmentPricePreview, type MovementFormCatalogs } from '../../services/api/administrationApi';
import { invalidateTenantQueries } from '../../serverState/invalidation';
import { useSession } from '../../session';
import { useModalAccessibility } from './useModalAccessibility';

type Props={open:boolean;onClose:()=>void;onCreated:()=>void};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'});
const money=(amount:number,currency:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency}).format(amount);
const frequencyNames:Record<string,string>={DAILY:'diaria',WEEKLY:'semanal',MONTHLY:'mensual',YEARLY:'anual'};
const frequencyName=(frequency:string|null|undefined)=>frequencyNames[frequency??'MONTHLY']??'mensual';
export function EnrollmentCreateModal({open,onClose,onCreated}:Props){
 const {clubId,permissions}=useSession(),canCollect=permissions.includes(PERMISSIONS.MOVEMENTS_CREATE);
 const dialogRef=useRef<HTMLElement>(null),keys=useRef(new Map<string,string>());
 const [people,setPeople]=useState<EnrollmentPerson[]>([]),[activities,setActivities]=useState<EnrollmentCatalogItem[]>([]),[catalogs,setCatalogs]=useState<MovementFormCatalogs|null>(null);
 const [personId,setPersonId]=useState(''),[search,setSearch]=useState(''),[activityId,setActivityId]=useState(''),[enrollmentDate,setEnrollmentDate]=useState(today());
 const [firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[document,setDocument]=useState(''),[phone,setPhone]=useState('');
 const [payNow,setPayNow]=useState(false),[accountId,setAccountId]=useState(''),[paymentMethodId,setPaymentMethodId]=useState('');
 const [enrollmentPay,setEnrollmentPay]=useState('0'),[feePay,setFeePay]=useState('0');
 const [manualEnrollmentPrice,setManualEnrollmentPrice]=useState('0'),[manualFeePrice,setManualFeePrice]=useState('0');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[priceLoading,setPriceLoading]=useState(false),[pricePreview,setPricePreview]=useState<EnrollmentPricePreview|null>(null);
 const activity=activities.find(item=>item.id===activityId),pricing=pricePreview??activity,currency=pricing?.currencyCode??activity?.currencyCode??'ARS';
 useModalAccessibility(dialogRef,open,()=>{if(!busy)onClose()});
 useEffect(()=>{if(!open)return;const c=new AbortController();void Promise.resolve().then(()=>{if(c.signal.aborted)return;setLoaded(false);setError('');return Promise.all([getEnrollmentFormCatalogs(c.signal),canCollect?getMovementFormCatalogs(c.signal):Promise.resolve(null)]);}).then(result=>{if(!result||c.signal.aborted)return;const [data,financial]=result;setPeople(data.people);setActivities(data.activities.filter(item=>item.generatesEnrollments!==false&&item.status!=='inactive'));setCatalogs(financial);setLoaded(true);}).catch(cause=>{if(!c.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudieron cargar los datos.');});return()=>c.abort();},[open,canCollect]);
 useEffect(()=>{if(!open||!activityId)return;const c=new AbortController();void Promise.resolve().then(()=>{if(c.signal.aborted)return;setPriceLoading(true);setPricePreview(null);return getEnrollmentPricePreview(activityId,enrollmentDate,c.signal);}).then(value=>{if(value&&!c.signal.aborted)setPricePreview(value);}).catch(cause=>{if(!c.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudo consultar el precio vigente.');}).finally(()=>{if(!c.signal.aborted)setPriceLoading(false);});return()=>c.abort();},[open,activityId,enrollmentDate]);
 if(!open)return null;
 const choosePerson=(id:string)=>{setPersonId(id);const p=people.find(item=>item.id===id);setFirstName(p?.firstName??'');setLastName(p?.lastName??'');setDocument(p?.dni??'');setPhone(p?.phone??'');};
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(event.currentTarget);
  const paymentDate=f.get('paymentDate');
  const initialPayment=payNow?{accountId,paymentMethodId,date:typeof paymentDate==='string'?paymentDate:'',enrollmentAmount:Number(enrollmentPay),feeAmount:Number(feePay)}:undefined;
  const input={personId:personId||undefined,person:{firstName,lastName,document,phone},activityId,enrollmentDate,
    ...(!pricing?.pricingConfigured?{enrollmentPrice:Number(manualEnrollmentPrice),feeAmount:Number(manualFeePrice)}:{}),initialPayment};
  if(payNow&&(!accountId||!paymentMethodId||Number(enrollmentPay)+Number(feePay)<=0)){setError('Elegí cuenta, medio de pago y un importe a cobrar.');setBusy(false);return;}
  const fingerprint=JSON.stringify({clubId,input}),key=keys.current.get(fingerprint)??crypto.randomUUID();keys.current.set(fingerprint,key);
  try{await createAdministrationEnrollment(input,key);keys.current.delete(fingerprint);invalidateTenantQueries(clubId);window.dispatchEvent(new Event('miclub:enrollment-created'));window.dispatchEvent(new Event('miclub:receivables-changed'));if(payNow)window.dispatchEvent(new Event('miclub:movement-created'));onCreated();onClose();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo registrar la inscripción.');}finally{setBusy(false);}
 };
 return <div className="draft-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section ref={dialogRef} tabIndex={-1} className="draft-modal draft-modal--large operation-modal" role="dialog" aria-modal="true" aria-labelledby="enrollment-form-title">
  <header className="operation-modal__header"><div><p className="eyebrow">Inscriptos</p><h2 id="enrollment-form-title">Cargar inscripción</h2><p>Registrá la persona, actividad y cargos iniciales.</p></div><button className="sector-modal__close" type="button" onClick={onClose} disabled={busy} aria-label="Cerrar">×</button></header>
  <form className="operation-modal__form" onSubmit={e=>void submit(e)}><div className="draft-modal__body operation-modal__body">
  {!loaded&&!error?<p role="status">Cargando personas y actividades…</p>:<><fieldset className="operation-modal__group"><legend>Persona</legend><div className="movement-form__grid">
   <label>Buscar persona<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre o identificación"/></label>
   <label>Persona<select value={personId} onChange={e=>choosePerson(e.target.value)}><option value="">Nueva persona</option>{people.filter(p=>`${p.firstName??''} ${p.lastName??''} ${p.dni??''}`.toLowerCase().includes(search.toLowerCase())).slice(0,40).map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName} · {p.dni||'sin identificación'}</option>)}</select></label>
   <label>Nombre<input value={firstName} onChange={e=>setFirstName(e.target.value)} required readOnly={Boolean(personId&&firstName)}/></label>
   <label>Apellido<input value={lastName} onChange={e=>setLastName(e.target.value)} required readOnly={Boolean(personId&&lastName)}/></label>
   <label>DNI o identificación<input value={document} onChange={e=>setDocument(e.target.value)} required readOnly={Boolean(personId&&people.find(p=>p.id===personId)?.dni)}/></label>
   <label>Teléfono<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" required readOnly={Boolean(personId&&people.find(p=>p.id===personId)?.phone)}/></label>
  </div></fieldset><fieldset className="operation-modal__group"><legend>Actividad y cargos iniciales</legend><div className="movement-form__grid"><label>Actividad<select required value={activityId} onChange={e=>{setActivityId(e.target.value);setPricePreview(null)}}><option value="">Seleccionar…</option>{activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
   <label>Fecha de inscripción<input name="enrollmentDate" type="date" required value={enrollmentDate} onChange={e=>{setEnrollmentDate(e.target.value);setPricePreview(null)}}/></label>
   {activity&&!priceLoading&&!pricing?.pricingConfigured&&<><label>Cargo de inscripción<input name="enrollmentPrice" type="number" min="0" step="1" required value={manualEnrollmentPrice} onChange={e=>setManualEnrollmentPrice(e.target.value)}/></label><label>Primera cuota<input name="feeAmount" type="number" min="0" step="1" required value={manualFeePrice} onChange={e=>setManualFeePrice(e.target.value)}/></label></>}
  </div>{priceLoading&&<p role="status">Consultando precio de la fecha elegida…</p>}{activity&&pricing&&<p className="operation-modal__hint" role="status">Inscripción {money(pricing.pricingConfigured?pricing.enrollmentPrice??0:Number(manualEnrollmentPrice),currency)} · Primera cuota {money(pricing.pricingConfigured?pricing.feePrice??0:Number(manualFeePrice),currency)} · frecuencia {frequencyName(pricing.feeFrequency)}. La primera cuota vence al inscribir.</p>}</fieldset>
  {canCollect&&<fieldset className="operation-modal__group"><legend>Cobro inicial</legend><label className="operation-modal__choice"><input type="checkbox" checked={payNow} onChange={e=>setPayNow(e.target.checked)}/> Cobrar ahora</label>{payNow&&<div className="movement-form__grid"><label>Cuenta<select value={accountId} onChange={e=>setAccountId(e.target.value)} required><option value="">Seleccionar…</option>{catalogs?.accounts.filter(a=>a.currencyCode===currency).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currencyCode}</option>)}</select></label><label>Medio de pago<select value={paymentMethodId} onChange={e=>setPaymentMethodId(e.target.value)} required><option value="">Seleccionar…</option>{catalogs?.paymentMethods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Fecha del cobro<input name="paymentDate" type="date" required defaultValue={today()}/></label><label>Abonar inscripción<input type="number" min="0" max={pricing?.pricingConfigured?pricing.enrollmentPrice??0:Number(manualEnrollmentPrice)} step="0.01" value={enrollmentPay} onChange={e=>setEnrollmentPay(e.target.value)}/></label><label>Abonar primera cuota<input type="number" min="0" max={pricing?.pricingConfigured?pricing.feePrice??0:Number(manualFeePrice)} step="0.01" value={feePay} onChange={e=>setFeePay(e.target.value)}/></label></div>}</fieldset>}
  {activity&&pricePreview&&<section className="operation-modal__summary" aria-label="Resumen de la inscripción"><h3>Resumen antes de confirmar</h3><p>{firstName||'Nombre'} {lastName||'Apellido'} · {activity.name} · {enrollmentDate}</p><p>Cargos: inscripción {money(pricing?.pricingConfigured?pricing.enrollmentPrice??0:Number(manualEnrollmentPrice),currency)} y primera cuota {money(pricing?.pricingConfigured?pricing.feePrice??0:Number(manualFeePrice),currency)}. {payNow?`Cobro inicial: ${money(Number(enrollmentPay)+Number(feePay),currency)}.`:'Sin cobro inicial.'}</p></section>}</>}
  {error&&<p className="sector-modal__error" role="alert">{error}</p>}</div><footer className="draft-modal__footer"><button type="button" className="ghost-btn" onClick={onClose} disabled={busy}>Cancelar</button><button type="submit" className="primary-btn" disabled={busy||!loaded||!activity||priceLoading||!pricePreview}>{busy?'Guardando…':'Registrar inscripción'}</button></footer></form>
 </section></div>;
}
