import { useEffect, useRef, useState, type FormEvent } from 'react';
import { PERMISSIONS, type AdministrationMovementDto } from '@miclub/shared';
import { apiJson } from '../../api';
import { useSession } from '../../session';
import { getMovementFormCatalogs } from '../../services/api/administrationApi';
import { invalidateMovementQueries } from '../../serverState/invalidation';
import { MovementPersonPicker } from './MovementPersonPicker';
import { MovementReceivableApplications, type ReceivableApplication } from './MovementReceivableApplications';

type Detail = { id:string;revision:number;movementDate:string;movementType:string;accountId:string|null;categoryId:string|null;sectorId:string;activityId:string|null;personId:string|null;paymentMethodId:string|null;concept:string;counterpartyText:string;amount:number;taxes:number;operationalStatus:string;receivableId:string|null;currencyCode:string;reconciledAt:string|null;voidedAt:string|null;applications:ReceivableApplication[] };
type Catalogs = Awaited<ReturnType<typeof getMovementFormCatalogs>>;

export function MovementFinanceActions({movement,onChanged}:{movement:AdministrationMovementDto;onChanged:()=>void}) {
  const {permissions,clubId}=useSession();
  const canCorrect=permissions.includes(PERMISSIONS.FINANCE_CORRECT);
  const canRefund=permissions.includes(PERMISSIONS.FINANCE_PAY);
  const [detail,setDetail]=useState<Detail|null>(null);
  const [catalogs,setCatalogs]=useState<Catalogs|null>(null);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const operationKeys=useRef(new Map<string,string>());
  const [mode,setMode]=useState<'correct'|'refund'|null>(null);
  const [personId,setPersonId]=useState('');const [activityId,setActivityId]=useState('');const [sectorId,setSectorId]=useState('');const [accountId,setAccountId]=useState('');const [movementType,setMovementType]=useState('');const [applications,setApplications]=useState<ReceivableApplication[]>([]);
  useEffect(()=>{if(!canCorrect&&!canRefund)return;const controller=new AbortController();void Promise.all([apiJson<Detail>(`/api/finance/movements/${movement.id}`,{signal:controller.signal}),getMovementFormCatalogs(controller.signal)]).then(([record,lists])=>{setDetail(record);setCatalogs(lists);setPersonId(record.personId??'');setActivityId(record.activityId??'');setSectorId(record.sectorId);setAccountId(record.accountId??'');setMovementType(record.movementType);setApplications(record.applications??[]);}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudo cargar el detalle financiero.');});return()=>controller.abort();},[movement.id,canCorrect,canRefund]);
  if(!canCorrect&&!canRefund)return null;
  const send=async(path:`/${string}`,body:unknown)=>{if(busy)return;setBusy(true);setError('');const fingerprint=JSON.stringify({clubId,path,body});const key=operationKeys.current.get(fingerprint)??crypto.randomUUID();operationKeys.current.set(fingerprint,key);try{await apiJson(path,{method:'POST',headers:{'idempotency-key':key},body:JSON.stringify(body)});operationKeys.current.delete(fingerprint);invalidateMovementQueries(clubId);window.dispatchEvent(new Event('miclub:movement-created'));window.dispatchEvent(new Event('miclub:receivables-changed'));onChanged();}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo guardar la operación.');}finally{setBusy(false);}};
  const correct=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!detail)return;const f=new FormData(event.currentTarget);const value=(key:string)=>{const raw=f.get(key);return typeof raw==='string'?raw:'';};const amount=Number(f.get('amount'));if(applications.reduce((sum,item)=>sum+item.amount,0)>amount){setError('Las aplicaciones superan el importe del movimiento.');return;}const changedReference=personId!==(detail.personId??'')||activityId!==(detail.activityId??'')||accountId!==(detail.accountId??'');void send(`/api/finance/movements/${detail.id}/correct`,{revision:detail.revision,reason:value('reason'),movement:{movementDate:value('movementDate'),movementType:movementType,accountId,categoryId:value('categoryId'),sectorId,activityId:activityId||null,personId:personId||null,paymentMethodId:value('paymentMethodId')||null,concept:value('concept'),counterpartyText:value('counterpartyText'),amount,taxes:Number(f.get('taxes')||0),operationalStatus:value('operationalStatus'),receivableId:changedReference?null:detail.receivableId},applications:applications.length?applications:changedReference?[]:undefined});};
  const refund=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!detail)return;const f=new FormData(event.currentTarget);void send(`/api/finance/movements/${detail.id}/refund`,{revision:detail.revision,accountId:f.get('accountId'),amount:Number(f.get('amount')),date:f.get('date'),reason:f.get('reason')});};
  const option=(name:string,label:string,items:{id:string;name:string}[],value:string|null,optional=false)=><label>{label}<select name={name} defaultValue={value??''} required={!optional}><option value="">{optional?'Sin asignar':'Seleccionar…'}</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;
  return <section className="movement-finance-actions"><h3>Operaciones financieras</h3>{error&&<p role="alert">{error}</p>}{!detail&&!error&&<p role="status">Cargando datos auditables…</p>}{detail&&catalogs&&<><div className="detail-modal__actions">{canCorrect&&<button type="button" onClick={()=>setMode(mode==='correct'?null:'correct')}>Corregir movimiento</button>}{canRefund&&detail.movementType==='INGRESOS'&&detail.operationalStatus==='COMPLETADO'&&<button type="button" onClick={()=>setMode(mode==='refund'?null:'refund')}>Registrar devolución</button>}</div>
    {mode==='correct'&&<form className="finance-form" onSubmit={correct} key={detail.revision}><p>La corrección conserva la versión anterior y exige un motivo. Cambiar persona, actividad o cuenta quita aplicaciones anteriores; revise las nuevas antes de guardar.</p><label>Fecha<input name="movementDate" type="date" defaultValue={detail.movementDate} required/></label><label>Tipo<select value={movementType} onChange={event=>{setMovementType(event.target.value);setApplications([]);}}><option value="INGRESOS">Ingreso</option><option value="EGRESOS">Egreso</option></select></label><label>Cuenta<select value={accountId} onChange={event=>{setAccountId(event.target.value);setApplications([]);}} required>{catalogs.accounts.map(item=><option key={item.id} value={item.id}>{item.name}{item.currencyCode?` · ${item.currencyCode}`:''}</option>)}</select></label>{option('categoryId','Categoría',catalogs.categories.filter(c=>c.isActive!==false),detail.categoryId)}<label>Sector<select value={sectorId} onChange={event=>{setSectorId(event.target.value);setActivityId('');setApplications([]);}} required>{catalogs.sectors.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Actividad<select value={activityId} onChange={event=>{setActivityId(event.target.value);setApplications([]);}}><option value="">Sin actividad</option>{catalogs.activities.filter(item=>item.sectorId===sectorId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><MovementPersonPicker value={personId} onChange={id=>{setPersonId(id);setApplications([]);}} initialLabel={movement.counterpartyText??undefined}/>{option('paymentMethodId','Medio de pago',catalogs.paymentMethods,detail.paymentMethodId,true)}<label>Concepto<input name="concept" defaultValue={detail.concept} required/></label><label>Contraparte<input name="counterpartyText" defaultValue={detail.counterpartyText} required/></label><label>Importe<input name="amount" type="number" min="0.01" step="0.01" defaultValue={detail.amount} required/></label><label>Impuestos<input name="taxes" type="number" min="0" step="0.01" defaultValue={detail.taxes}/></label><label>Estado<select name="operationalStatus" defaultValue={detail.operationalStatus}><option value="COMPLETADO">Completado</option><option value="PENDIENTE">Pendiente</option><option value="ANULADO">Anulado</option></select></label>{movementType==='INGRESOS'&&<MovementReceivableApplications personId={personId} activityId={activityId} currencyCode={catalogs.accounts.find(item=>item.id===accountId)?.currencyCode??''} value={applications} onChange={setApplications}/>}<label>Motivo<input name="reason" required/></label><button disabled={busy}>Guardar corrección</button></form>}
    {mode==='refund'&&<form className="finance-form" onSubmit={refund}>{option('accountId','Cuenta de devolución',catalogs.accounts,detail.accountId)}<label>Importe<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Fecha<input name="date" type="date" min={detail.movementDate} required/></label><label>Motivo<input name="reason" required/></label><button disabled={busy}>Registrar devolución</button></form>}
  </>}</section>;
}
