import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { PERMISSIONS, type AdministrationEnrollmentDto } from '@miclub/shared';
import { apiJson } from '../../api';
import { getAdministrationEnrollments, getMovementFormCatalogs, type MovementFormCatalogs } from '../../services/api/administrationApi';
import { invalidateTenantQueries } from '../../serverState/invalidation';
import { useSession } from '../../session';
import { useModalAccessibility } from './useModalAccessibility';

type Charge={id:string;concept:string;chargeKind:string|null;periodMonth:number|null;dueDate:string|null;amount:number;paidAmount:number;cancelledAmount:number;outstandingAmount:number;currencyCode:string;status:string};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'});
const format=(amount:number,currency:string)=>new Intl.NumberFormat('es-AR',{style:'currency',currency}).format(amount);
export function QuotaModal({open,onClose}:{open:boolean;onClose:()=>void}){
 const {clubId,permissions}=useSession(),canGenerate=permissions.includes(PERMISSIONS.ENROLLMENTS_CREATE),canCollect=permissions.includes(PERMISSIONS.MOVEMENTS_CREATE);
 const ref=useRef<HTMLElement>(null),keys=useRef(new Map<string,string>());
 const [search,setSearch]=useState(''),[enrollments,setEnrollments]=useState<AdministrationEnrollmentDto[]>([]),[enrollmentId,setEnrollmentId]=useState('');
 const [charges,setCharges]=useState<Charge[]>([]),[catalogs,setCatalogs]=useState<MovementFormCatalogs|null>(null),[accountId,setAccountId]=useState(''),[methodId,setMethodId]=useState('');
 const [selectedId,setSelectedId]=useState(''),[amount,setAmount]=useState(''),[month,setMonth]=useState(today().slice(0,7)),[documentType,setDocumentType]=useState<'DNI'|'CUIL'|'REGISTRO'>('DNI'),[documentValue,setDocumentValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useModalAccessibility(ref,open,()=>{if(!busy)onClose()});
 const loadCharges=useCallback(async(id:string,signal?:AbortSignal)=>{const items:Charge[]=[];let total=0;do{const page=await apiJson<{items:Charge[];total:number}>(`/api/receivables?enrollmentId=${encodeURIComponent(id)}&limit=100&offset=${items.length}` as `/${string}`,{signal,cache:'no-store'});items.push(...page.items);total=page.total;if(!page.items.length&&items.length<total)throw new Error('La lista de cuotas cambió. Reintentá.');}while(items.length<total);setCharges(items);},[]);
 useEffect(()=>{if(!open)return;const c=new AbortController();void Promise.all([getAdministrationEnrollments(1,{search:''},c.signal),canCollect?getMovementFormCatalogs(c.signal):Promise.resolve(null)]).then(([page,financial])=>{if(!c.signal.aborted){setEnrollments(page.items);setCatalogs(financial);}}).catch(cause=>{if(!c.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudieron cargar las inscripciones.');});return()=>c.abort();},[open,canCollect]);
 useEffect(()=>{if(!open||!enrollmentId)return;const c=new AbortController();void Promise.resolve().then(()=>{if(!c.signal.aborted)return loadCharges(enrollmentId,c.signal);}).catch(cause=>{if(!c.signal.aborted)setError(cause instanceof Error?cause.message:'No se pudieron cargar las cuotas.');});return()=>c.abort();},[open,enrollmentId,loadCharges]);
 if(!open)return null;
 const selected=charges.find(c=>c.id===selectedId),enrollment=enrollments.find(e=>e.id===enrollmentId);
 const searchPeople=async()=>{setError('');try{const page=await getAdministrationEnrollments(1,{search});setEnrollments(page.items);}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo buscar.');}};
 const send=async(path:`/${string}`,payload:Record<string,unknown>)=>{setBusy(true);setError('');setNotice('');const body={...payload,reason:'Operación de cuota desde Administración'},fingerprint=JSON.stringify({clubId,path,body}),key=keys.current.get(fingerprint)??crypto.randomUUID();keys.current.set(fingerprint,key);try{const result=await apiJson<{generated?:number;existing?:number;rejected?:Array<{reason:string}>}>(path,{method:'POST',headers:{'idempotency-key':key},body:JSON.stringify(body)});keys.current.delete(fingerprint);invalidateTenantQueries(clubId);window.dispatchEvent(new Event('miclub:receivables-changed'));window.dispatchEvent(new Event('miclub:movement-created'));await loadCharges(enrollmentId);setNotice(path.endsWith('/generate')?`${result.generated??0} cuotas generadas; ${result.existing??0} ya existían.${result.rejected?.length?` ${result.rejected.length} rechazadas: ${result.rejected.map(item=>item.reason).join('; ')}`:''}`:'Cobro registrado.');}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo completar la operación.');}finally{setBusy(false);}};
 const generate=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(enrollmentId)void send('/api/finance/receivables/generate',{month,enrollmentId});};
 const collect=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const rawDate=new FormData(event.currentTarget).get('date');if(selectedId)void send(`/api/finance/receivables/${selectedId}/collect`,{amount:Number(amount),accountId,paymentMethodId:methodId,date:typeof rawDate==='string'?rawDate:'',documentType,documentValue});};
 return <div className="sector-modal__backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section ref={ref} tabIndex={-1} className="sector-modal movement-form-modal" role="dialog" aria-modal="true" aria-labelledby="quota-title">
  <header className="sector-modal__header"><div><p className="eyebrow">Inscriptos</p><h2 id="quota-title">Cargar cuota</h2><p>Generá cargos y registrá cobros totales o parciales.</p></div><button className="sector-modal__close" type="button" onClick={onClose} disabled={busy} aria-label="Cerrar">×</button></header>
  <div className="movement-form"><label>Buscar inscripción<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Persona o actividad"/></label><button type="button" onClick={()=>void searchPeople()}>Buscar</button><label>Inscripción<select value={enrollmentId} onChange={e=>{setEnrollmentId(e.target.value);setSelectedId('');setCharges([]);}}><option value="">Seleccionar…</option>{enrollments.map(e=><option key={e.id} value={e.id}>{e.displayName||`${e.firstName} ${e.lastName}`} · {e.activityName} · #{e.sequenceNumber}</option>)}</select></label>
  {enrollment&&<p>{enrollment.activityName} · {enrollment.displayName||`${enrollment.firstName} ${enrollment.lastName}`}</p>}
  {enrollmentId&&canGenerate&&<form className="finance-form" onSubmit={generate}><h3>Generar cuotas del mes</h3><label>Mes<input type="month" value={month} onChange={e=>setMonth(e.target.value)} required/></label><button disabled={busy}>Generar faltantes</button></form>}
  {enrollmentId&&<section><h3>Cargos y saldos</h3>{charges.length===0?<p>Esta inscripción todavía no tiene cargos.</p>:<div className="finance-table"><table><thead><tr><th>Concepto</th><th>Vencimiento</th><th>Importe</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody>{charges.map(c=><tr key={c.id}><td>{c.concept}</td><td>{c.dueDate?.slice(0,10)??'Sin fecha'}</td><td>{format(c.amount,c.currencyCode)}</td><td>{format(c.paidAmount,c.currencyCode)}</td><td>{format(c.outstandingAmount,c.currencyCode)}</td><td>{c.status}{canCollect&&c.outstandingAmount>0&&(c.chargeKind==='FEE'||c.chargeKind==null&&c.periodMonth!=null)&&<button type="button" onClick={()=>{setSelectedId(c.id);setAmount(String(c.outstandingAmount));setDocumentValue(enrollment?.dni??'');}}>Cobrar</button>}</td></tr>)}</tbody></table></div>}</section>}
  {selected&&canCollect&&<form className="finance-form" onSubmit={collect}><h3>Cobrar cuota</h3><p>Saldo: {format(selected.outstandingAmount,selected.currencyCode)}</p><label>Importe<input type="number" min="0.01" max={selected.outstandingAmount} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Fecha<input name="date" type="date" defaultValue={today()} required/></label><label>Tipo de identificación<select value={documentType} onChange={e=>setDocumentType(e.target.value as typeof documentType)}><option value="DNI">DNI</option><option value="CUIL">CUIL</option><option value="REGISTRO">N.º de registro</option></select></label><label>Identificación de contraparte<input value={documentValue} onChange={e=>setDocumentValue(e.target.value)} required/></label><label>Cuenta<select value={accountId} onChange={e=>setAccountId(e.target.value)} required><option value="">Seleccionar…</option>{catalogs?.accounts.filter(a=>a.currencyCode===selected.currencyCode).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currencyCode}</option>)}</select></label><label>Medio de pago<select value={methodId} onChange={e=>setMethodId(e.target.value)} required><option value="">Seleccionar…</option>{catalogs?.paymentMethods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button disabled={busy}>{busy?'Registrando…':'Registrar cobro'}</button></form>}
  {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error}</p>}</div>
 </section></div>;
}
