import { useCallback, useEffect, useState } from 'react';
import type { ApprovalRequest } from '@miclub/shared';
import { approveRequest, getRequests, rejectRequest } from '../../services/api/requestsApi';

const labels: Record<ApprovalRequest['status'], string> = { PENDING:'Pendiente', APPROVED:'Aprobada', REJECTED:'Rechazada', CANCELLED:'Cancelada', EXPIRED:'Vencida' };
export function RequestPanel() {
  const [items,setItems]=useState<ApprovalRequest[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{setItems((await getRequests(signal)).items)}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'No se pudieron cargar las solicitudes.')}finally{if(!signal?.aborted)setLoading(false)}},[]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]);
  const decide=async(item:ApprovalRequest,decision:'approve'|'reject')=>{const reason=window.prompt(decision==='approve'?'Motivo de aprobación (opcional)':'Motivo de rechazo (opcional)')??undefined;if(reason===undefined)return;setBusy(item.id);setError(null);try{const changed=decision==='approve'?await approveRequest(item.id,reason):await rejectRequest(item.id,reason);setItems(current=>current.map(value=>value.id===changed.id?changed:value))}catch(e){setError(e instanceof Error?e.message:'No se pudo resolver la solicitud.')}finally{setBusy(null)}};
  return <section className="section-panel request-panel" aria-labelledby="request-panel-title"><div className="section-header"><div><p className="eyebrow">Control</p><h3 id="request-panel-title">Solicitudes</h3><p>Revisá y registrá decisiones. Sólo se procesan tipos con handlers seguros.</p></div><button className="icon-btn" onClick={()=>void load()} disabled={loading}>Actualizar</button></div>
    {error&&<p className="task-panel__error" role="alert">{error}</p>}{loading?<p>Cargando solicitudes…</p>:items.length===0?<p className="task-panel__empty">No hay solicitudes.</p>:<ul className="request-panel__list">{items.map(item=><li key={item.id}><div><strong>{item.title}</strong>{item.description&&<span>{item.description}</span>}<small>Tipo: {item.requestType} · {new Date(item.createdAt).toLocaleString('es-AR')}</small></div><span className="task-panel__status" data-status={item.status}>{labels[item.status]}</span>{item.status==='PENDING'&&<div className="request-panel__actions"><button type="button" className="icon-btn" disabled={busy===item.id} onClick={()=>void decide(item,'approve')}>Aprobar</button><button type="button" className="icon-btn" disabled={busy===item.id} onClick={()=>void decide(item,'reject')}>Rechazar</button></div>}</li>)}</ul>}</section>;
}
