import type { AdministrationActivityDto, AdministrationSectorDto, AdministrationWorkerDto, AdministrationWorkerMutationDto, OnboardingActivityDraft, OnboardingSectorDraft, OnboardingWorkerDraft } from '@miclub/shared';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { apiJson } from '../../api';
import { useStepPersistence } from '../Onboarding/StepPersistence';
import { WorkerDetailModal } from './WorkerDetailModal';
import { archiveAdministrationWorker, createAdministrationSector, createAdministrationWorker, getAdministrationActivities, getAdministrationSectors, getAdministrationWorkers, getSectorTemplates, updateAdministrationWorker, type SectorTemplate } from '../../services/api/administrationApi';

const message = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;
const mutation = (path: `/${string}`, method: 'PATCH'|'POST', body: unknown) => apiJson(path, { method, body: JSON.stringify(body) });

export function SectorSetupForm() {
  const [items,setItems]=useState<AdministrationSectorDto[]>([]), [templates,setTemplates]=useState<SectorTemplate[]>([]), [error,setError]=useState(''), [busy,setBusy]=useState(false), [editing,setEditing]=useState<string>();
  const load=useCallback(async()=>{setBusy(true);setError('');try{const [sectors,catalog]=await Promise.all([getAdministrationSectors(),getSectorTemplates()]);setItems(sectors.items);setTemplates(catalog.items);}catch(e){setError(message(e,'No se pudieron consultar los sectores.'));}finally{setBusy(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const persistence=useMemo(()=>({save:async()=>{const response=await getAdministrationSectors();setItems(response.items);if(response.items.length<3)throw new Error('El servidor todavía no confirmó los sectores obligatorios.');},canContinue:items.length>=3}),[items.length]); useStepPersistence(persistence);
  const run=async(operation:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await operation();setEditing(undefined);await load();}catch(e){setError(message(e,'No se pudo guardar el sector.'));setBusy(false);}};
  const create=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const d=new FormData(event.currentTarget);void run(()=>createAdministrationSector({templateId:String(d.get('templateId')),color:String(d.get('color')),status:String(d.get('status')) as 'active'|'inactive'|'under_repair'}));};
  return <section className="setup-manager" aria-busy={busy}><header><h3>Sectores configurados</h3><button type="button" onClick={()=>void load()} disabled={busy}>Actualizar</button></header>{error&&<p role="alert">{error}</p>}<ul>{items.map(s=><li key={s.id}><strong>{s.name}</strong> <span>{s.operationalStatus}</span>{s.isSystem?<em> Sistema · protegido</em>:<>{editing===s.id?<form onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name'));void run(()=>mutation(`/api/sectors/${s.id}`,'PATCH',{updatedAt:s.updatedAt,name}));}}><input name="name" defaultValue={s.name} required/><button>Guardar</button></form>:<button type="button" onClick={()=>setEditing(s.id)}>Editar</button>}<button type="button" onClick={()=>void run(()=>mutation(`/api/sectors/${s.id}/status`,'PATCH',{updatedAt:s.updatedAt,status:s.operationalStatus==='active'?'inactive':'active'}))}>Cambiar estado</button><button type="button" onClick={()=>void run(()=>mutation(`/api/sectors/${s.id}/archive`,'POST',{updatedAt:s.updatedAt}))}>Archivar</button></>}</li>)}</ul><form className="setup-form" onSubmit={create}><legend>Agregar sector desde el catálogo global</legend><label>Plantilla<select name="templateId" required defaultValue=""><option value="" disabled>Seleccionar…</option>{templates.map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></label><label>Color<input name="color" type="color" defaultValue="#2563EB"/></label><label>Estado<select name="status"><option value="active">Activo</option><option value="inactive">Inactivo</option><option value="under_repair">En reparación</option></select></label><button disabled={busy}>Crear sector</button></form></section>;
}

export function WorkerSetupForm() {
 const [items,setItems]=useState<AdministrationWorkerDto[]>([]),[selected,setSelected]=useState<AdministrationWorkerDto>(),[creating,setCreating]=useState(false),[error,setError]=useState('');
 const load=useCallback(async()=>{try{setItems((await getAdministrationWorkers()).items);setError('');}catch(e){setError(message(e,'No se pudieron consultar los trabajadores.'));}},[]); useEffect(()=>{void load();},[load]);
 const persistence=useMemo(()=>({save:async()=>{const r=await getAdministrationWorkers();setItems(r.items);if(!r.items.length)throw new Error('El servidor todavía no confirmó ningún trabajador.');},canContinue:items.length>0}),[items.length]);useStepPersistence(persistence);
 const save=async(input:AdministrationWorkerMutationDto)=>{if(selected)await updateAdministrationWorker(selected.id,input);else await createAdministrationWorker(input);await load();};
 return <section className="setup-manager"><header><h3>Equipo del club</h3><button type="button" onClick={()=>setCreating(true)}>Nuevo trabajador</button></header>{error&&<p role="alert">{error}</p>}<ul>{items.map(w=><li key={w.id}><button type="button" onClick={()=>setSelected(w)}><strong>{w.displayName}</strong> · {w.role}</button>{w.roleGuard?.isDirector&&<em> Director protegido</em>}</li>)}</ul>{creating&&<WorkerDetailModal onClose={()=>setCreating(false)} onSave={save}/>} {selected&&<WorkerDetailModal worker={selected} onClose={()=>setSelected(undefined)} onSave={save} onArchive={selected.roleGuard?.canRemoveDirectorRole?async()=>{await apiJson(`/api/administration/workers/${selected.id}`,{method:'DELETE'});await load();}:undefined}/>}</section>;
}

type CatalogItem={id?:string;name?:string;displayName?:string;iconKey?:string};
export function ActivitySetupForm() {
 const [items,setItems]=useState<AdministrationActivityDto[]>([]),[sectors,setSectors]=useState<CatalogItem[]>([]),[instructors,setInstructors]=useState<CatalogItem[]>([]),[icons,setIcons]=useState<CatalogItem[]>([]),[editing,setEditing]=useState<AdministrationActivityDto>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const [a,s,i,ic]=await Promise.all([getAdministrationActivities(),apiJson<CatalogItem[]>('/api/sectors'),apiJson<CatalogItem[]>('/api/instructors'),apiJson<{items:CatalogItem[]}>('/api/administration/activity-icons')]);setItems(a.items);setSectors(s);setInstructors(i);setIcons(ic.items);setError('');}catch(e){setError(message(e,'No se pudo consultar la configuración de actividades.'));}finally{setBusy(false);}},[]);useEffect(()=>{void load();},[load]);
 const persistence=useMemo(()=>({save:async()=>{const r=await getAdministrationActivities();setItems(r.items);if(!r.items.length)throw new Error('Creá una actividad y esperá la confirmación del servidor para continuar.');},canContinue:items.length>0}),[items.length]);useStepPersistence(persistence);
 const run=async(op:()=>Promise<unknown>)=>{setBusy(true);try{await op();setEditing(undefined);await load();}catch(e){setError(message(e,'No se pudo guardar la actividad.'));setBusy(false);}};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),mode=String(d.get('settlementMode'));const body={sectorId:String(d.get('sectorId')),instructorId:String(d.get('instructorId'))||null,name:String(d.get('name')),iconKey:String(d.get('iconKey')),color:String(d.get('color')),enrollmentFee:Number(d.get('enrollmentFee')),settlement:mode==='FIXED'?{mode:'FIXED' as const,monthlyFixedFee:Number(d.get('economicValue')),clubSharePercentage:null,effectiveFrom:new Date().toISOString().slice(0,10)}:{mode:'VARIABLE' as const,monthlyFixedFee:null,clubSharePercentage:Number(d.get('economicValue')),effectiveFrom:new Date().toISOString().slice(0,10)},instructorCommissionPercent:0,status:String(d.get('status')),notes:mode==='FIXED'?`Término económico FIXED: ARS ${Number(d.get('economicValue'))}`:'Término económico VARIABLE'};void run(()=>mutation(editing?`/api/activities/${editing.id}`:'/api/activities',editing?'PATCH':'POST',editing?{...body,updatedAt:editing.updatedAt}:body));};
 return <section className="setup-manager" aria-busy={busy}><header><h3>Actividades configuradas</h3><button type="button" onClick={()=>void load()}>Actualizar</button></header>{error&&<p role="alert">{error}</p>}<ul>{items.map(a=><li key={a.id}><strong>{a.name}</strong> · {a.status}<button type="button" onClick={()=>setEditing(a)}>Editar</button><button type="button" onClick={()=>void run(()=>mutation(`/api/activities/${a.id}/status`,'PATCH',{updatedAt:a.updatedAt,status:a.status==='active'?'inactive':'active'}))}>Cambiar estado</button><button type="button" onClick={()=>void run(()=>mutation(`/api/activities/${a.id}/archive`,'POST',{updatedAt:a.updatedAt}))}>Archivar</button></li>)}</ul><form className="setup-form" onSubmit={submit}><legend>{editing?'Editar':'Nueva'} actividad</legend><label>Nombre<input name="name" required defaultValue={editing?.name}/></label><label>Sector<select name="sectorId" required defaultValue={editing?.sectorId??''}><option value="">Seleccionar…</option>{sectors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Instructor<select name="instructorId" required defaultValue={editing?.instructorId??''}><option value="">Seleccionar…</option>{instructors.map(i=><option key={i.id} value={i.id}>{i.displayName??i.name}</option>)}</select></label><label>Icono<select name="iconKey" defaultValue={editing?.iconKey??'other'}>{icons.map(i=><option key={i.iconKey} value={i.iconKey}>{i.displayName}</option>)}</select></label><label>Color<input name="color" type="color" defaultValue={editing?.color??'#2563EB'}/></label><label>Inscripción<input name="enrollmentFee" type="number" min="0" defaultValue={editing?.enrollmentFee??0}/></label><label>Término económico<select name="settlementMode" defaultValue={editing?.settlementMode??'VARIABLE'}><option value="FIXED">FIXED · monto fijo</option><option value="VARIABLE">VARIABLE · porcentaje del club</option></select></label><label>Monto / porcentaje<input name="economicValue" type="number" min="0" max="100000000" defaultValue={editing?.settlementMode==='FIXED'?editing.settlementFixedAmount??0:editing?.clubCommissionPercent??0}/></label><label>Estado<select name="status" defaultValue={editing?.status??'inactive'}><option value="inactive">Inactiva</option><option value="active">Activa</option></select></label><button disabled={busy}>Guardar actividad</button>{editing&&<button type="button" onClick={()=>setEditing(undefined)}>Cancelar</button>}</form></section>;
}

/** Pure editors used by onboarding. Administration wrappers above own all immediate persistence. */
export function LocalSectorSetupForm({items,onChange}:{items:OnboardingSectorDraft[];onChange:(items:OnboardingSectorDraft[])=>void}) {
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),name=String(d.get('name'));onChange([...items,{clientId:crypto.randomUUID(),templateId:'',code:name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-'),name,color:String(d.get('color')),status:String(d.get('status')) as OnboardingSectorDraft['status'],isSystem:false}]);e.currentTarget.reset();};
 return <section className="setup-manager"><h3>Sectores del club</h3><ul>{items.map(x=><li key={x.clientId}><strong>{x.name}</strong>{x.isSystem?<em> Sistema · provisionado</em>:<button type="button" onClick={()=>onChange(items.filter(i=>i.clientId!==x.clientId))}>Quitar</button>}</li>)}</ul><form className="setup-form" onSubmit={submit}><label>Nombre<input name="name" required/></label><label>Color<input name="color" type="color" defaultValue="#2563EB"/></label><label>Estado<select name="status"><option value="active">Activo</option><option value="inactive">Inactivo</option><option value="under_repair">En reparación</option></select></label><button>Agregar al borrador</button></form></section>;
}
export function LocalWorkerSetupForm({items,onChange}:{items:OnboardingWorkerDraft[];onChange:(items:OnboardingWorkerDraft[])=>void}) {
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),get=(k:string)=>String(d.get(k)??'');onChange([...items,{clientId:crypto.randomUUID(),firstName:get('firstName'),lastName:get('lastName'),dni:get('dni'),email:get('email'),password:get('password'),role:get('role') as OnboardingWorkerDraft['role'],paymentMode:'VARIABLE',monthlyFixedAmount:null}]);e.currentTarget.reset();};
 return <section className="setup-manager"><h3>Trabajadores</h3><ul>{items.map(x=><li key={x.clientId}>{x.firstName} {x.lastName}<button type="button" onClick={()=>onChange(items.filter(i=>i.clientId!==x.clientId))}>Quitar</button></li>)}</ul><form className="setup-form" onSubmit={submit}><label>Nombre<input name="firstName" required/></label><label>Apellido<input name="lastName" required/></label><label>DNI<input name="dni" pattern="[0-9]{7,9}" required/></label><label>Correo<input name="email" type="email" required/></label><label>Contraseña<input name="password" type="password" minLength={10} required/></label><label>Rol<select name="role"><option>TRABAJADOR</option><option>INSTRUCTOR</option></select></label><button>Agregar al borrador</button></form></section>;
}
export function LocalActivitySetupForm({items,sectors,onChange}:{items:OnboardingActivityDraft[];sectors:OnboardingSectorDraft[];onChange:(items:OnboardingActivityDraft[])=>void}) {
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);onChange([...items,{clientId:crypto.randomUUID(),name:String(d.get('name')),sectorClientId:String(d.get('sector')),instructorClientId:null,iconKey:'other',color:'#2563EB',enrollmentFee:0,settlementMode:'VARIABLE',economicValue:0,status:'inactive'}]);e.currentTarget.reset();};
 return <section className="setup-manager"><h3>Actividades</h3><ul>{items.map(x=><li key={x.clientId}>{x.name}<button type="button" onClick={()=>onChange(items.filter(i=>i.clientId!==x.clientId))}>Quitar</button></li>)}</ul><form className="setup-form" onSubmit={submit}><label>Nombre<input name="name" required/></label><label>Sector<select name="sector" required><option value="">Seleccionar…</option>{sectors.map(x=><option key={x.clientId} value={x.clientId}>{x.name}</option>)}</select></label><button>Agregar al borrador</button></form></section>;
}
