import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { TASK_STATUSES, type Task, type TaskStatus } from '@miclub/shared';
import { archiveTask, createTask, getTasks, updateTaskStatus } from '../../services/api/tasksApi';

const labels: Record<Task['displayStatus'], string> = { PENDING: 'Pendiente', IN_PROGRESS: 'En curso', COMPLETED: 'Completada', CANCELLED: 'Cancelada', OVERDUE: 'Vencida' };
export function TaskPanel({ canCreate, canEdit }: { canCreate: boolean; canEdit: boolean }) {
  const [tasks,setTasks]=useState<Task[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setError(null);try{setTasks((await getTasks(signal)).items)}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'No se pudieron cargar las tareas.')}finally{if(!signal?.aborted)setLoading(false)}},[]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort()},[load]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);setError(null);try{const created=await createTask({title:String(form.get('title')),description:String(form.get('description')||'')||null,dueAt:String(form.get('dueAt')||'')?new Date(String(form.get('dueAt'))).toISOString():null,priority:'NORMAL'});setTasks(current=>[created,...current]);event.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:'No se pudo crear la tarea.')}finally{setSaving(false)}};
  const status=async(task:Task,next:TaskStatus)=>{setSaving(true);try{const changed=await updateTaskStatus(task,next);setTasks(current=>current.map(item=>item.id===changed.id?changed:item))}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar la tarea.')}finally{setSaving(false)}};
  const archive=async(task:Task)=>{setSaving(true);try{await archiveTask(task);setTasks(current=>current.filter(item=>item.id!==task.id))}catch(e){setError(e instanceof Error?e.message:'No se pudo archivar la tarea.')}finally{setSaving(false)}};
  return <section className="section-panel task-panel" aria-labelledby="task-panel-title"><div className="section-header"><div><p className="eyebrow">Seguimiento</p><h3 id="task-panel-title">Tareas</h3><p>Organizá pendientes y vencimientos del equipo.</p></div><button className="icon-btn" onClick={()=>void load()} disabled={loading}>Actualizar</button></div>
    {canCreate ? <form className="task-panel__form" onSubmit={submit}><label>Título<input name="title" maxLength={160} required placeholder="Nueva tarea" /></label><label>Descripción<input name="description" maxLength={1000} placeholder="Detalle opcional" /></label><label>Vencimiento<input name="dueAt" type="datetime-local" /></label><button className="icon-btn" disabled={saving}>Crear tarea</button></form> : <p className="worker-list__notice">Podés consultar tareas, pero no crear nuevas.</p>}
    {error&&<p className="task-panel__error" role="alert">{error}</p>}{loading?<p>Cargando tareas…</p>:tasks.length===0?<p className="task-panel__empty">No hay tareas activas.</p>:<ul className="task-panel__list">{tasks.map(task=><li key={task.id}><div><strong>{task.title}</strong>{task.description&&<span>{task.description}</span>}<small>{task.dueAt?`Vence ${new Date(task.dueAt).toLocaleString('es-AR')}`:'Sin vencimiento'}</small></div><span className="task-panel__status" data-status={task.displayStatus}>{labels[task.displayStatus]}</span>{canEdit && <select aria-label={`Estado de ${task.title}`} value={task.status} disabled={saving} onChange={e=>void status(task,e.target.value as TaskStatus)}>{TASK_STATUSES.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select>}{canEdit && <button className="icon-btn" disabled={saving} onClick={()=>void archive(task)} type="button">Archivar</button>}</li>)}</ul>}</section>;
}
