import assert from "node:assert/strict";
import test from "node:test";
import type { OnboardingState, OnboardingStep, OnboardingStepOutcome } from "@miclub/shared";
import { createOnboardingService, type OnboardingStore } from "./onboardingService.js";

const state=(overrides:Partial<OnboardingState>={}):OnboardingState=>({status:"NOT_STARTED",currentStep:1,startedAt:null,completedAt:null,createdAt:"2026-08-12T00:00:00.000Z",updatedAt:"2026-08-12T00:00:00.000Z",movementCount:0,enrollmentCount:0,shouldShow:true,completedSteps:[],skippedSteps:[],migrationAvailable:false,...overrides});
const actor={userId:"user-1",membershipId:"membership-1",clubId:"club-1"};
const fixture=(initial=state())=>{let current=initial;let writes=0;const store:OnboardingStore={read:async()=>current,advance:async(_actor,target:OnboardingStep,outcome:OnboardingStepOutcome)=>{if(target!==current.currentStep+1)throw new Error("invalid transition");const departed=current.currentStep;writes++;current=state({...current,status:"IN_PROGRESS",currentStep:target,completedSteps:outcome==="COMPLETED"?[...current.completedSteps,departed]:current.completedSteps,skippedSteps:outcome==="SKIPPED"?[...current.skippedSteps,departed]:current.skippedSteps,startedAt:current.startedAt??"2026-08-12T01:00:00.000Z"});return current;},complete:async()=>{if(current.status!=="COMPLETED"){const resolved=new Set([...current.completedSteps,...current.skippedSteps]);if(current.currentStep!==7||resolved.size!==6)throw new Error("pending");writes++;current=state({...current,status:"COMPLETED",completedAt:"2026-08-12T02:00:00.000Z",shouldShow:false});}return current;},saveOpeningBalances:async()=>({batchId:"batch-1"})};return {service:createOnboardingService(store),writes:()=>writes};};

test("refresh conserva el hito actual y no genera escrituras ni loop",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:4,completedSteps:[1,2],skippedSteps:[3]}));const first=await f.service.read(actor.clubId);const refreshed=await f.service.read(actor.clubId);assert.deepEqual(refreshed,first);assert.equal(refreshed.shouldShow,true);assert.equal(f.writes(),0);});
test("club con movimientos pero onboarding pendiente sigue mostrándose",async()=>{const f=fixture(state({movementCount:4,enrollmentCount:2}));assert.equal((await f.service.read(actor.clubId)).shouldShow,true);});
test("persiste omisiones autorizadas separadas de pasos completados",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:6,completedSteps:[1,2,3,4,5]}));const next=await f.service.advance(actor,7,"SKIPPED");assert.deepEqual(next.completedSteps,[1,2,3,4,5]);assert.deepEqual(next.skippedSteps,[6]);});
test("rechaza intentos de omitir pasos obligatorios antes de escribir",()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:3,completedSteps:[1],skippedSteps:[2]}));assert.throws(()=>f.service.advance(actor,4,"SKIPPED"),(error:unknown)=>error instanceof Error&&error.message.includes("obligatorio")&&(error as Error&{code?:string}).code==="ONBOARDING_SKIP_NOT_ALLOWED");assert.equal(f.writes(),0);});
test("permite omitir saldos cuando se importará el historial",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:2,completedSteps:[1]}));const next=await f.service.advance(actor,3,"SKIPPED");assert.deepEqual(next.skippedSteps,[2]);});
test("permite omitir Migración",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:6,completedSteps:[1,2,3,4,5]}));const next=await f.service.advance(actor,7,"SKIPPED");assert.deepEqual(next.skippedSteps,[6]);});
test("no permite finalizar sin resolver los seis pasos",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:7,completedSteps:[1,2]}));await assert.rejects(()=>f.service.complete(actor),/pending/);});
test("finalización es idempotente y no vuelve a mostrar onboarding",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:7,completedSteps:[1,2,3,4,5],skippedSteps:[6]}));assert.equal((await f.service.complete(actor)).shouldShow,false);await f.service.complete(actor);assert.equal(f.writes(),1);});
