import assert from "node:assert/strict";
import test from "node:test";
import type { OnboardingDraft, OnboardingState, OnboardingStep, OnboardingStepOutcome } from "@miclub/shared";
import { isOnboardingVisible } from "../repositories/onboardingRepository.js";
import { createOnboardingService, type OnboardingStore } from "./onboardingService.js";

const state=(overrides:Partial<OnboardingState>={}):OnboardingState=>({status:"NOT_STARTED",currentStep:1,startedAt:null,completedAt:null,createdAt:"2026-08-12T00:00:00.000Z",updatedAt:"2026-08-12T00:00:00.000Z",movementCount:0,enrollmentCount:0,shouldShow:true,completedSteps:[],skippedSteps:[],migrationAvailable:false,...overrides});
const actor={userId:"user-1",membershipId:"membership-1",clubId:"club-1"};
const draft:OnboardingDraft={idempotencyKey:"test-key-123",openingBalances:{currency:"ARS",cash:0,bank:0,usdCash:0},sectors:[],workers:[],activities:[],pendingImport:null};
const fixture=(initial=state())=>{let current=initial;let writes=0;const store:OnboardingStore={read:async()=>current,advance:async(_actor,target:OnboardingStep,outcome:OnboardingStepOutcome)=>{if(target!==current.currentStep+1)throw new Error("invalid transition");const departed=current.currentStep;writes++;current=state({...current,status:"IN_PROGRESS",currentStep:target,completedSteps:outcome==="COMPLETED"?[...current.completedSteps,departed]:current.completedSteps,skippedSteps:outcome==="SKIPPED"?[...current.skippedSteps,departed]:current.skippedSteps,startedAt:current.startedAt??"2026-08-12T01:00:00.000Z"});return current;},complete:async()=>{if(current.status!=="COMPLETED"){if(current.currentStep!==7||![1,2].every(step=>current.completedSteps.includes(step as OnboardingStep)))throw new Error("pending");writes++;current=state({...current,status:"COMPLETED",completedAt:"2026-08-12T02:00:00.000Z",shouldShow:isOnboardingVisible(current.movementCount,current.enrollmentCount,"COMPLETED","2026-08-12T02:00:00.000Z")});}return {state:current,created:{openingBalanceBatchId:"batch-1",sectorIds:[],workerIds:[],activityIds:[]}};},saveOpeningBalances:async()=>({batchId:"batch-1"})};return {service:createOnboardingService(store),writes:()=>writes};};

test("refresh conserva el hito actual y no genera escrituras ni loop",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:4,completedSteps:[1,2],skippedSteps:[3]}));const first=await f.service.read(actor.clubId);const refreshed=await f.service.read(actor.clubId);assert.deepEqual(refreshed,first);assert.equal(refreshed.shouldShow,true);assert.equal(f.writes(),0);});
test("visibilidad depende de finalización explícita y no de movimientos, inscripciones o saldos cero",()=>{for(const [movementCount,enrollmentCount] of [[0,0],[1,0],[0,1],[1,1]] as const){assert.equal(isOnboardingVisible(movementCount,enrollmentCount,"IN_PROGRESS",null),true);assert.equal(isOnboardingVisible(movementCount,enrollmentCount,"COMPLETED","2026-08-12T02:00:00.000Z"),false);}});
test("avanzar es una operación de compatibilidad sin persistencia",async()=>{const initial=state();const f=fixture(initial);for(const target of [2,3,4,5,6,7] as OnboardingStep[])await f.service.advance(actor,target,target>3?"SKIPPED":"COMPLETED");assert.deepEqual(await f.service.read(actor.clubId),initial);assert.equal(f.writes(),0);});
test("no actualiza columnas de progreso legado durante la edición",async()=>{const initial=state({status:"IN_PROGRESS",currentStep:5,completedSteps:[1,2],skippedSteps:[3,4]});const f=fixture(initial);const response=await f.service.advance(actor,6,"SKIPPED");assert.deepEqual(response,initial);assert.equal(f.writes(),0);});
test("rechaza intentos de omitir Bienvenida o Saldos antes de escribir",()=>{for(const [currentStep,target] of [[1,2],[2,3]] as const){const f=fixture(state({status:"IN_PROGRESS",currentStep}));assert.throws(()=>f.service.advance(actor,target,"SKIPPED"),(error:unknown)=>error instanceof Error&&error.message.includes("obligatorio")&&(error as Error&{code?:string}).code==="ONBOARDING_SKIP_NOT_ALLOWED");assert.equal(f.writes(),0);}});
test("permite omitir pasos opcionales sin dejar rastros durables",async()=>{const initial=state({status:"IN_PROGRESS",currentStep:3,completedSteps:[1,2]});const f=fixture(initial);for(const target of [4,5,6,7] as OnboardingStep[])await f.service.advance(actor,target,"SKIPPED");assert.deepEqual(await f.service.read(actor.clubId),initial);assert.equal(f.writes(),0);});
test("no permite finalizar antes del paso siete ni sin los hitos obligatorios",async()=>{await assert.rejects(()=>fixture(state({status:"IN_PROGRESS",currentStep:6,completedSteps:[1,2]})).service.complete(actor,draft),/pending/);await assert.rejects(()=>fixture(state({status:"IN_PROGRESS",currentStep:7,completedSteps:[1],skippedSteps:[3,4,5,6]})).service.complete(actor,draft),/pending/);});
test("finalización devuelve COMPLETED oculto y un login posterior no reabre el modal",async()=>{const f=fixture(state({status:"IN_PROGRESS",currentStep:7,completedSteps:[1,2],skippedSteps:[3,4,5,6]}));const completed=(await f.service.complete(actor,draft)).state;assert.equal(completed.status,"COMPLETED");assert.equal(completed.shouldShow,false);assert.deepEqual(completed.completedSteps,[1,2]);assert.deepEqual(completed.skippedSteps,[3,4,5,6]);assert.equal((await f.service.read(actor.clubId)).shouldShow,false);await f.service.complete(actor,draft);assert.equal(f.writes(),1);});
