import { ONBOARDING_DRAFT_CONTRACT_VERSION, PERMISSIONS, type OnboardingStep, type OnboardingStepOutcome } from "@miclub/shared";
import { Router, type Request } from "express";
import { requirePermission } from "../middleware/authorization.js";
import { onboardingService } from "../services/onboardingService.js";
import asyncHandler from "./asyncHandler.js";
import { isCompleteOnboardingRequest, isOpeningBalancesRequest } from "./onboardingValidation.js";
import { deleteOnboardingPhoto, ONBOARDING_PHOTO_POLICY, storeOnboardingPhoto } from "../services/onboardingPhotoStore.js";
const router=Router();
const actor=(req:Request)=>({userId:req.auth!.userId,membershipId:req.auth!.membershipId,clubId:req.auth!.clubId,requestId:req.requestId,ip:req.ip,userAgent:req.get("user-agent")});
router.get("/onboarding",requirePermission(PERMISSIONS.ONBOARDING_READ),asyncHandler(async(req,res)=>res.json(await onboardingService.read(req.auth!.clubId))));
router.patch("/onboarding/advance",requirePermission(PERMISSIONS.ONBOARDING_WRITE),asyncHandler(async(req,res)=>{const body=req.body as Record<string,unknown>;if(Object.keys(body).some(k=>!["currentStep","outcome"].includes(k))||!Number.isInteger(body.currentStep)||Number(body.currentStep)<2||Number(body.currentStep)>7||!["COMPLETED","SKIPPED"].includes(String(body.outcome)))return res.status(400).json({code:"VALIDATION_ERROR",message:"Se requieren el próximo currentStep y un outcome válido"});try{return res.json(await onboardingService.advance(actor(req),body.currentStep as OnboardingStep,body.outcome as OnboardingStepOutcome));}catch(error){if(typeof error==='object'&&error&&'code'in error)return res.status(409).json({code:error.code,message:error instanceof Error?error.message:"Conflicto de onboarding"});throw error;}}));
router.post("/onboarding/opening-balances",requirePermission(PERMISSIONS.ONBOARDING_WRITE),asyncHandler(async(req,res)=>{if(!isOpeningBalancesRequest(req.body))return res.status(400).json({code:"VALIDATION_ERROR",message:"La moneda soportada, los saldos no negativos y la clave son obligatorios"});return res.json(await onboardingService.saveOpeningBalances(actor(req),req.body));}));
const multipartFile=(raw:Buffer,boundary:string)=>{const start=raw.indexOf(Buffer.from("\r\n\r\n"));if(start<0)return null;const headers=raw.subarray(0,start).toString();const end=raw.indexOf(Buffer.from(`\r\n--${boundary}`),start+4);if(end<0||!headers.includes('name="file"'))return null;return {data:raw.subarray(start+4,end),mime:headers.match(/Content-Type:\s*([^\r\n]+)/i)?.[1]?.trim()??""};};
router.post("/onboarding/photos",requirePermission(PERMISSIONS.ONBOARDING_WRITE),asyncHandler(async(req,res)=>{
 const contentType=req.get("content-type")??"",boundary=contentType.match(/boundary=(?:"([^"]+)"|([^;]+))/i)?.slice(1).find(Boolean);if(!boundary)return res.status(400).json({code:"MULTIPART_REQUIRED",message:"Se requiere multipart/form-data."});
 const chunks:Buffer[]=[];let size=0;for await(const chunk of req){size+=(chunk as Buffer).length;if(size>ONBOARDING_PHOTO_POLICY.maxBytes+64*1024)return res.status(413).json({code:"PHOTO_SIZE_LIMIT",message:"La foto supera el máximo de 5 MB."});chunks.push(chunk as Buffer);}
 const file=multipartFile(Buffer.concat(chunks),boundary);if(!file)return res.status(400).json({code:"FILE_REQUIRED",message:"Falta el campo file."});
 try{return res.status(201).json(await storeOnboardingPhoto(req.auth!.clubId,file.data,file.mime));}catch(error){if(typeof error==='object'&&error&&'code'in error)return res.status(String(error.code)==='PHOTO_SIZE_LIMIT'?413:422).json({code:error.code,message:error instanceof Error?error.message:"Foto inválida."});throw error;}
}));
router.delete("/onboarding/photos/:fileId",requirePermission(PERMISSIONS.ONBOARDING_WRITE),asyncHandler(async(req,res)=>{const fileId=String(req.params.fileId);if(!/^[0-9a-f-]{36}$/i.test(fileId))return res.status(400).json({code:"VALIDATION_ERROR",message:"Identificador inválido."});await deleteOnboardingPhoto(req.auth!.clubId,fileId);return res.status(204).end();}));
const onboardingErrorStatus=(code:string)=>code==='ONBOARDING_SCHEMA_UNAVAILABLE'?503:code.includes('ALREADY')||code.includes('CONFLICT')?409:code.includes('INVALID')||code.includes('FORBIDDEN')||code.includes('MISSING')?422:400;
router.post("/onboarding/complete",requirePermission(PERMISSIONS.ONBOARDING_WRITE),asyncHandler(async(req,res)=>{const version=(req.body as {draft?:{contractVersion?:unknown}})?.draft?.contractVersion;if(version!==undefined&&version!==ONBOARDING_DRAFT_CONTRACT_VERSION)return res.status(409).json({code:"ONBOARDING_DRAFT_VERSION_UNSUPPORTED",message:`Versión ${typeof version==='string'||typeof version==='number'?version:'desconocida'} no soportada; se requiere ${ONBOARDING_DRAFT_CONTRACT_VERSION}. Reiniciá el borrador.`});if(!isCompleteOnboardingRequest(req.body))return res.status(400).json({code:"VALIDATION_ERROR",message:"El borrador completo contiene datos inválidos"});try{return res.json(await onboardingService.complete(actor(req),req.body.draft));}catch(error){if(typeof error==='object'&&error&&'code'in error){const code=String(error.code);return res.status(onboardingErrorStatus(code)).json({code,message:error instanceof Error?error.message:"No se pudo completar el onboarding"});}throw error;}}));
export default router;
