import type { ContactedRecentResponse, Member } from '@miclub/shared';
import { formatArPeso } from '../../utils';
import type { SortBy } from './types';
import { formatLastPayment } from './formatters';
import { Icon } from './Icon';

type Props = { filtered: Member[]; selected: string[]; setSelected: React.Dispatch<React.SetStateAction<string[]>>; contactedRecent: ContactedRecentResponse; changeSort: (sortBy: SortBy) => void; renderSortIndicator: (sortBy: SortBy) => string; toggleAllDebtors: () => void; clearSelection: () => void };
export const MembersTable = ({ filtered, selected, setSelected, contactedRecent, changeSort, renderSortIndicator, toggleAllDebtors, clearSelection }: Props) => <>
  <div className="actions-row"><p><strong>Resultados visibles:</strong> {filtered.length} · <strong>Seleccionados:</strong> {selected.length} · <strong>Contactados últimos 30 días:</strong> {contactedRecent.memberIds.length}</p><button className="icon-btn" onClick={toggleAllDebtors}><Icon label="☑" />Seleccionar todos los visibles</button><button className="icon-btn" onClick={clearSelection}><Icon label="⌫" />Limpiar selección</button></div>
  {filtered.length === 0 ? <p>No hay resultados con los filtros actuales.</p> : <div className="members-table-wrap"><table className="members-table"><thead><tr><th></th><th><button className="sortable-header" onClick={() => changeSort('nombre')}>Nombre {renderSortIndicator('nombre')}</button></th><th>Teléfono</th><th><button className="sortable-header" onClick={() => changeSort('actividad')}>Actividad {renderSortIndicator('actividad')}</button></th><th><button className="sortable-header" onClick={() => changeSort('cuota')}>Cuota {renderSortIndicator('cuota')}</button></th><th><button className="sortable-header" onClick={() => changeSort('lastPaymentAt')}>Último pago {renderSortIndicator('lastPaymentAt')}</button></th><th>Instructor</th><th><button className="sortable-header" onClick={() => changeSort('sourceSheet')}>Hoja {renderSortIndicator('sourceSheet')}</button></th><th><button className="sortable-header" onClick={() => changeSort('estado')}>Estado {renderSortIndicator('estado')}</button></th><th><button className="sortable-header" onClick={() => changeSort('lastContactAt')}>Contacto {renderSortIndicator('lastContactAt')}</button></th></tr></thead><tbody>{filtered.map(m => { const recent = contactedRecent.byMemberId[m.id]; return <tr key={m.id} className={recent ? 'recent-contact-row' : ''}><td><input type="checkbox" disabled={m.estado !== 'Adeudando'} checked={selected.includes(m.id)} onChange={() => setSelected(prev => prev.includes(m.id) ? prev.filter(id => id !== m.id) : [...prev, m.id])} /></td><td>{m.nombre} {m.apellido}</td><td>{m.telefono}</td><td>{m.actividad ?? '-'}</td><td>{m.cuota !== undefined ? formatArPeso(m.cuota) : '-'}</td><td><span className={m.lastPaymentAt ? 'last-payment-badge' : 'last-payment-badge last-payment-badge--empty'} title={m.lastPaymentConcept ? `Concepto: ${m.lastPaymentConcept}` : undefined}>{formatLastPayment(m)}</span></td><td>{m.instructor ?? '-'}</td><td>{m.sourceSheet}</td><td>{m.estado}</td><td>{recent ? <span className="recent-contact-badge" title="Mensaje enviado en los últimos 30 días">📩 Contactado: {new Date(recent.lastSentAt).toLocaleDateString('es-AR')}</span> : '-'}</td></tr>; })}</tbody></table></div>}
</>;
