import type { OnboardingState, OnboardingStatus, OnboardingStep } from "@miclub/shared";
import { getPostgresPool, type QueryExecutor } from "../db/postgres.js";
import { withTransaction } from "../db/transaction.js";
import { auditService } from "../services/auditService.js";

export type OnboardingActor = { userId: string; membershipId: string; clubId: string; requestId?: string; ip?: string; userAgent?: string };
type Row = { club_id:string; status:OnboardingStatus; current_step:number; started_at:Date|string|null; completed_at:Date|string|null; created_at:Date|string; updated_at:Date|string; movement_count:string|number; enrollment_count:string|number };
const iso=(v:Date|string|null)=>v==null?null:new Date(v).toISOString();
const map=(r:Row):OnboardingState=>{const movementCount=Number(r.movement_count),enrollmentCount=Number(r.enrollment_count);return {status:r.status,currentStep:r.current_step as OnboardingStep,startedAt:iso(r.started_at),completedAt:iso(r.completed_at),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!,movementCount,enrollmentCount,shouldShow:movementCount===0&&enrollmentCount===0&&r.status!=="COMPLETED"};};
const select=`select o.*, (select count(*) from miclub.movements m where m.club_id=o.club_id) movement_count,
 (select count(*) from miclub.enrollments e where e.club_id=o.club_id) enrollment_count from miclub.club_onboarding o where o.club_id=$1`;
const ensure=async(db:QueryExecutor,clubId:string)=>{await db.query("insert into miclub.club_onboarding (club_id) values ($1) on conflict (club_id) do nothing",[clubId]);return map((await db.query<Row>(select,[clubId])).rows[0]);};
export const readOnboarding=async(clubId:string)=>ensure(await getPostgresPool(),clubId);
const audit=(actor:OnboardingActor,action:string,before:OnboardingState,after:OnboardingState,db:QueryExecutor)=>auditService.sensitiveChange({action,result:"success",userId:actor.userId,membershipId:actor.membershipId,clubId:actor.clubId,entityType:"club_onboarding",entityId:actor.clubId,requestId:actor.requestId,ip:actor.ip,userAgent:actor.userAgent,oldData:before as unknown as Record<string,unknown>,newData:after as unknown as Record<string,unknown>},db);
export const advanceOnboarding=async(actor:OnboardingActor,step:OnboardingStep)=>withTransaction(async db=>{const before=await ensure(db,actor.clubId);if(before.status==="COMPLETED"||step<=before.currentStep&&before.status==="IN_PROGRESS")return before;await db.query(`update miclub.club_onboarding set status='IN_PROGRESS',current_step=greatest(current_step,$2),started_at=coalesce(started_at,now()),updated_at=now() where club_id=$1`,[actor.clubId,step]);const after=map((await db.query<Row>(select,[actor.clubId])).rows[0]);await audit(actor,"onboarding.advance",before,after,db);return after;},await getPostgresPool());
export const completeOnboarding=async(actor:OnboardingActor)=>withTransaction(async db=>{const before=await ensure(db,actor.clubId);if(before.status==="COMPLETED")return before;await db.query(`update miclub.club_onboarding set status='COMPLETED',completed_at=coalesce(completed_at,now()),started_at=coalesce(started_at,now()),updated_at=now() where club_id=$1`,[actor.clubId]);const after=map((await db.query<Row>(select,[actor.clubId])).rows[0]);await audit(actor,"onboarding.complete",before,after,db);return after;},await getPostgresPool());
