import assert from "node:assert/strict";
import test from "node:test";
import { setPostgresPoolForTests, type PgClient, type PgPool } from "../db/postgres.js";
import { decideRequest, type RequestActor } from "./requestsRepository.js";

const actor:RequestActor={userId:"11111111-1111-4111-8111-111111111111",membershipId:"22222222-2222-4222-8222-222222222222",clubId:"33333333-3333-4333-8333-333333333333"};
const row=(type:string)=>({id:"44444444-4444-4444-8444-444444444444",title:"Revisión",description:null,status:"pending",target_entity_type:type,target_entity_id:null,requested_by_user_id:null,assigned_to_user_id:null,decision_reason:null,decided_at:null,expires_at:null,created_at:"2026-08-06T10:00:00Z",updated_at:"2026-08-06T10:00:00Z"});
const fakePool=(handler:(sql:string)=>{rows:Record<string,unknown>[]})=>{const queries:string[]=[];const client={query:async(sql:string)=>{queries.push(sql);if(["BEGIN","COMMIT","ROLLBACK"].includes(sql))return {rows:[]};return handler(sql)},release:()=>undefined} as PgClient;setPostgresPoolForTests({connect:async()=>client,query:client.query,end:async()=>undefined} as PgPool);return queries};
test.afterEach(()=>setPostgresPoolForTests(undefined));
test("rechaza request_type sin handler sin ejecutar metadata ni mutar",async()=>{const queries=fakePool(sql=>{if(sql.includes("from miclub.approval_requests"))return {rows:[row("arbitrary_command")]};throw new Error(`SQL inesperado: ${sql}`)});assert.deepEqual(await decideRequest(actor,row("").id,"approved",null),{kind:"unsupported_type"});assert.equal(queries.some(sql=>sql.includes("update miclub.approval_requests")||sql.includes("audit_log")),false)});
test("MANUAL_REVIEW registra decisión y auditoría en la misma transacción",async()=>{const before=row("manual_review");const after={...before,status:"approved",decided_at:"2026-08-06T10:01:00Z",updated_at:"2026-08-06T10:01:00Z"};const queries=fakePool(sql=>{if(sql.includes("from miclub.approval_requests"))return {rows:[before]};if(sql.includes("update miclub.approval_requests"))return {rows:[after]};if(sql.includes("INSERT INTO miclub.audit_log"))return {rows:[{id:"audit-1"}]};throw new Error(`SQL inesperado: ${sql}`)});const result=await decideRequest(actor,before.id,"approved","Conforme");assert.equal(result.kind,"updated");assert.ok(queries.some(sql=>sql.includes("INSERT INTO miclub.audit_log")))});
